#ifndef SCUDA_API_H
#define SCUDA_API_H

// 4.11 Initialization and Cleanup
#define RPC_nvmlInitWithFlags 0
#define RPC_nvmlInit_v2 1
#define RPC_nvmlShutdown 2

// 4.12 Error reporting
#define RPC_nvmlErrorString 3

// 4.14 System Queries
#define RPC_nvmlSystemGetDriverVersion 4
// #define RPC_nvmlSystemGetDriverVersion_v2 5
// #define RPC_nvmlSystemGetDriverBranch 6
#define RPC_nvmlSystemGetHicVersion 7
#define RPC_nvmlSystemGetNVMLVersion 8
#define RPC_nvmlSystemGetProcessName 9
#define RPC_nvmlSystemGetTopologyGpuSet 10

// 4.15 Unit Queries
#define RPC_nvmlUnitGetCount 11
#define RPC_nvmlUnitGetDevices 12
#define RPC_nvmlUnitGetFanSpeedInfo 13
#define RPC_nvmlUnitGetHandleByIndex 14
#define RPC_nvmlUnitGetLedState 15
#define RPC_nvmlUnitGetPsuInfo 16
#define RPC_nvmlUnitGetTemperature 17
#define RPC_nvmlUnitGetUnitInfo 18

// 4.16 Device Queries
#define RPC_nvmlDeviceGetAPIRestriction 19
#define RPC_nvmlDeviceGetAdaptiveClockInfoStatus 20
#define RPC_nvmlDeviceGetApplicationsClock 21
#define RPC_nvmlDeviceGetArchitecture 22
#define RPC_nvmlDeviceGetAttributes_v2 23
#define RPC_nvmlDeviceGetAutoBoostedClocksEnabled 24
#define RPC_nvmlDeviceGetBAR1MemoryInfo 25
#define RPC_nvmlDeviceGetBoardId 26
#define RPC_nvmlDeviceGetBoardPartNumber 27
#define RPC_nvmlDeviceGetBrand 28
#define RPC_nvmlDeviceGetBridgeChipInfo 29
#define RPC_nvmlDeviceGetBusType 30
#define RPC_nvmlDeviceGetC2cModeInfoV 31
#define RPC_nvmlDeviceGetClkMonStatus 32
#define RPC_nvmlDeviceGetClock 33
#define RPC_nvmlDeviceGetClockInfo 34
#define RPC_nvmlDeviceGetClockOffsets 35
#define RPC_nvmlDeviceGetComputeMode 36
#define RPC_nvmlDeviceGetComputeRunningProcesses_v3 37
#define RPC_nvmlDeviceGetConfComputeGpuAttestationReport 38
#define RPC_nvmlDeviceGetConfComputeGpuCertificate 39
#define RPC_nvmlDeviceGetConfComputeMemSizeInfo 40
#define RPC_nvmlDeviceGetConfComputeProtectedMemoryUsage 41
#define RPC_nvmlDeviceGetCount_v2 42
#define RPC_nvmlDeviceGetCudaComputeCapability 43
#define RPC_nvmlDeviceGetCurrPcieLinkGeneration 44
#define RPC_nvmlDeviceGetCurrPcieLinkWidth 45
#define RPC_nvmlDeviceGetCurrentClocksEventReasons 46
#define RPC_nvmlDeviceGetCurrentClocksThrottleReasons 47
#define RPC_nvmlDeviceGetDecoderUtilization 48
#define RPC_nvmlDeviceGetDefaultApplicationsClock 49
#define RPC_nvmlDeviceGetDefaultEccMode 50
#define RPC_nvmlDeviceGetDetailedEccErrors 51
#define RPC_nvmlDeviceGetDisplayActive 52
#define RPC_nvmlDeviceGetDisplayMode 53
#define RPC_nvmlDeviceGetDriverModel_v2 54
#define RPC_nvmlDeviceGetDynamicPstatesInfo 55
#define RPC_nvmlDeviceGetEccMode 56
#define RPC_nvmlDeviceGetEncoderCapacity 57
#define RPC_nvmlDeviceGetEncoderSessions 58
#define RPC_nvmlDeviceGetEncoderStats 59
#define RPC_nvmlDeviceGetEncoderUtilization 60
#define RPC_nvmlDeviceGetEnforcedPowerLimit 61
#define RPC_nvmlDeviceGetFBCSessions 62
#define RPC_nvmlDeviceGetFBCStats 63
#define RPC_nvmlDeviceGetFanControlPolicy_v2 64
#define RPC_nvmlDeviceGetFanSpeed 65
#define RPC_nvmlDeviceGetFanSpeed_v2 66
#define RPC_nvmlDeviceGetGpcClkMinMaxVfOffset 67
#define RPC_nvmlDeviceGetGpcClkVfOffset 68
#define RPC_nvmlDeviceGetGpuFabricInfo 69
#define RPC_nvmlDeviceGetGpuFabricInfoV 70
#define RPC_nvmlDeviceGetGpuMaxPcieLinkGeneration 71
#define RPC_nvmlDeviceGetGpuOperationMode 72
#define RPC_nvmlDeviceGetGraphicsRunningProcesses_v3 73
#define RPC_nvmlDeviceGetGspFirmwareMode 74
#define RPC_nvmlDeviceGetGspFirmwareVersion 75
#define RPC_nvmlDeviceGetHandleByIndex_v2 76
#define RPC_nvmlDeviceGetHandleByPciBusId_v2 77
#define RPC_nvmlDeviceGetHandleBySerial 78
#define RPC_nvmlDeviceGetHandleByUUID 79
#define RPC_nvmlDeviceGetIndex 80
#define RPC_nvmlDeviceGetInforomConfigurationChecksum 81
#define RPC_nvmlDeviceGetInforomImageVersion 82
#define RPC_nvmlDeviceGetInforomVersion 83
#define RPC_nvmlDeviceGetIrqNum 84
#define RPC_nvmlDeviceGetJpgUtilization 85
#define RPC_nvmlDeviceGetLastBBXFlushTime 86
#define RPC_nvmlDeviceGetMPSComputeRunningProcesses_v3 87
#define RPC_nvmlDeviceGetMaxClockInfo 88
#define RPC_nvmlDeviceGetMaxCustomerBoostClock 89
#define RPC_nvmlDeviceGetMaxPcieLinkGeneration 90
#define RPC_nvmlDeviceGetMaxPcieLinkWidth 91
#define RPC_nvmlDeviceGetMemClkMinMaxVfOffset 92
#define RPC_nvmlDeviceGetMemClkVfOffset 93
#define RPC_nvmlDeviceGetMemoryBusWidth 94
#define RPC_nvmlDeviceGetMemoryErrorCounter 95
#define RPC_nvmlDeviceGetMemoryInfo 96
#define RPC_nvmlDeviceGetMemoryInfo_v2 97
#define RPC_nvmlDeviceGetMinMaxClockOfPState 98
#define RPC_nvmlDeviceGetMinMaxFanSpeed 99
#define RPC_nvmlDeviceGetMinorNumber 100
#define RPC_nvmlDeviceGetModuleId 101
#define RPC_nvmlDeviceGetMultiGpuBoard 102
#define RPC_nvmlDeviceGetName 103
#define RPC_nvmlDeviceGetNumFans 104
#define RPC_nvmlDeviceGetNumGpuCores 105
#define RPC_nvmlDeviceGetOfaUtilization 106
#define RPC_nvmlDeviceGetP2PStatus 107
#define RPC_nvmlDeviceGetPciInfoExt 108
#define RPC_nvmlDeviceGetPciInfo_v3 109
#define RPC_nvmlDeviceGetPcieLinkMaxSpeed 110
#define RPC_nvmlDeviceGetPcieReplayCounter 111
#define RPC_nvmlDeviceGetPcieSpeed 112
#define RPC_nvmlDeviceGetPcieThroughput 113
#define RPC_nvmlDeviceGetPerformanceState 114
#define RPC_nvmlDeviceGetPersistenceMode 115
#define RPC_nvmlDeviceGetPowerManagementDefaultLimit 116
#define RPC_nvmlDeviceGetPowerManagementLimit 117
#define RPC_nvmlDeviceGetPowerManagementLimitConstraints 118
#define RPC_nvmlDeviceGetPowerManagementMode 119
#define RPC_nvmlDeviceGetPowerSource 120
#define RPC_nvmlDeviceGetPowerState 121
#define RPC_nvmlDeviceGetPowerUsage 122
#define RPC_nvmlDeviceGetProcessUtilization 123
#define RPC_nvmlDeviceGetProcessesUtilizationInfo 124
#define RPC_nvmlDeviceGetRemappedRows 125
#define RPC_nvmlDeviceGetRetiredPages 126
#define RPC_nvmlDeviceGetRetiredPagesPendingStatus 127
#define RPC_nvmlDeviceGetRetiredPages_v2 128
#define RPC_nvmlDeviceGetRowRemapperHistogram 129
#define RPC_nvmlDeviceGetRunningProcessDetailList 130
#define RPC_nvmlDeviceGetSamples 131
#define RPC_nvmlDeviceGetSerial 132
#define RPC_nvmlDeviceGetSramEccErrorStatus 133
#define RPC_nvmlDeviceGetSupportedClocksEventReasons 134
#define RPC_nvmlDeviceGetSupportedClocksThrottleReasons 135
#define RPC_nvmlDeviceGetSupportedGraphicsClocks 136
#define RPC_nvmlDeviceGetSupportedMemoryClocks 137
#define RPC_nvmlDeviceGetSupportedPerformanceStates 138
#define RPC_nvmlDeviceGetTargetFanSpeed 139
#define RPC_nvmlDeviceGetTemperature 140
#define RPC_nvmlDeviceGetTemperatureThreshold 141
#define RPC_nvmlDeviceGetThermalSettings 142
#define RPC_nvmlDeviceGetTopologyCommonAncestor 143
#define RPC_nvmlDeviceGetTopologyNearestGpus 144
#define RPC_nvmlDeviceGetTotalEccErrors 145
#define RPC_nvmlDeviceGetTotalEnergyConsumption 146
#define RPC_nvmlDeviceGetUUID 147
#define RPC_nvmlDeviceGetUtilizationRates 148
#define RPC_nvmlDeviceGetVbiosVersion 149
#define RPC_nvmlDeviceGetViolationStatus 150
#define RPC_nvmlDeviceOnSameBoard 151
#define RPC_nvmlDeviceSetClockOffsets 152
#define RPC_nvmlDeviceSetConfComputeUnprotectedMemSize 153
#define RPC_nvmlDeviceSetPowerManagementLimit_v2 154
#define RPC_nvmlDeviceValidateInforom 155
#define RPC_nvmlSystemGetConfComputeCapabilities 156
#define RPC_nvmlSystemGetConfComputeGpusReadyState 157
#define RPC_nvmlSystemGetConfComputeKeyRotationThresholdInfo 158
#define RPC_nvmlSystemGetConfComputeSettings 159
#define RPC_nvmlSystemGetConfComputeState 160
#define RPC_nvmlSystemSetConfComputeGpusReadyState 161

// 4.17 Unit Commands
#define RPC_nvmlUnitSetLedState 162

// 4.18 Device Commands
#define RPC_nvmlDeviceClearEccErrorCounts 163
#define RPC_nvmlDeviceResetApplicationsClocks 164
#define RPC_nvmlDeviceResetGpuLockedClocks 165
#define RPC_nvmlDeviceResetMemoryLockedClocks 166
#define RPC_nvmlDeviceSetAPIRestriction 167
#define RPC_nvmlDeviceSetApplicationsClocks 168
#define RPC_nvmlDeviceSetAutoBoostedClocksEnabled 169
#define RPC_nvmlDeviceSetComputeMode 170
#define RPC_nvmlDeviceSetDefaultAutoBoostedClocksEnabled 171
#define RPC_nvmlDeviceSetDefaultFanSpeed_v2 172
#define RPC_nvmlDeviceSetDriverModel 173
#define RPC_nvmlDeviceSetEccMode 174
#define RPC_nvmlDeviceSetFanControlPolicy 175
#define RPC_nvmlDeviceSetFanSpeed_v2 176
#define RPC_nvmlDeviceSetGpcClkVfOffset 177
#define RPC_nvmlDeviceSetGpuLockedClocks 178
#define RPC_nvmlDeviceSetGpuOperationMode 179
#define RPC_nvmlDeviceSetMemClkVfOffset 180
#define RPC_nvmlDeviceSetMemoryLockedClocks 181
#define RPC_nvmlDeviceSetPersistenceMode 182
#define RPC_nvmlDeviceSetPowerManagementLimit 183
#define RPC_nvmlDeviceSetTemperatureThreshold 184

// 4.19 NvLink Methods
#define RPC_nvmlDeviceFreezeNvLinkUtilizationCounter 185
#define RPC_nvmlDeviceGetNvLinkCapability 186
#define RPC_nvmlDeviceGetNvLinkErrorCounter 187
#define RPC_nvmlDeviceGetNvLinkRemoteDeviceType 188
#define RPC_nvmlDeviceGetNvLinkRemotePciInfo_v2 189
#define RPC_nvmlDeviceGetNvLinkState 190
#define RPC_nvmlDeviceGetNvLinkUtilizationControl 191
#define RPC_nvmlDeviceGetNvLinkUtilizationCounter 192
#define RPC_nvmlDeviceGetNvLinkVersion 193
#define RPC_nvmlDeviceResetNvLinkErrorCounters 194
#define RPC_nvmlDeviceResetNvLinkUtilizationCounter 195
#define RPC_nvmlDeviceSetNvLinkDeviceLowPowerThreshold 196
#define RPC_nvmlDeviceSetNvLinkUtilizationControl 197
#define RPC_nvmlSystemGetNvlinkBwMode 198
#define RPC_nvmlSystemSetNvlinkBwMode 199

// 4.20 Event Handling Methods
#define RPC_nvmlDeviceGetSupportedEventTypes 200
#define RPC_nvmlDeviceRegisterEvents 201
#define RPC_nvmlEventSetCreate 202
#define RPC_nvmlEventSetFree 203
#define RPC_nvmlEventSetWait_v2 204

// cuda
#define RPC_cuLinkCreate_v2 206
#define RPC_cuLinkAddData_v2 207
#define RPC_cuLinkComplete 208
#define RPC_cuModuleLoadData 209
#define RPC_cuModuleUnload 210
#define RPC_cuGetErrorString 211
#define RPC_cuLinkDestroy 212
#define RPC_cuModuleGetFunction 213
#define RPC_cuFuncSetAttribute 214
#define RPC_cuLaunchKernel 215
#define RPC_cuGetErrorName 216
#define RPC_cuModuleLoadFatBinary 217
#define RPC_cuModuleLoadDataEx 218
#define RPC_cuLinkAddFile_v2 219
#define RPC_cuInit 220
#define RPC_cuFuncGetAttribute 221
#define RPC_cuCtxPushCurrent 222
#define RPC_cuCtxPopCurrent 223
#define RPC_cuCtxGetDevice 224
#define RPC_cuDevicePrimaryCtxRetain 225
#define RPC_cuDevicePrimaryCtxRelease 226
#define RPC_cuDevicePrimaryCtxReset 227
#define RPC_cuDeviceGet 228
#define RPC_cuDeviceGetAttribute 229
#define RPC_cuStreamSynchronize 230
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessor 231
#define RPC_cuLaunchKernelEx 232
#define RPC_cuMemcpyDtoH_v2 233
#define RPC_cuModuleGetGlobal_v2 234
#define RPC_cuGetProcAddress_v2 235
#define RPC_cuDeviceGetCount 236
#define RPC_cudaGetDeviceCount 237
#define RPC_cuDriverGetVersion 238

#endif