FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libnvidia-ml-dev \
    python3 \
    python3-pip \
    python3-venv \
    ninja-build \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /home

COPY . .

RUN cd codegen && \
    python3 -m venv venv && \
    venv/bin/pip install -r requirements.txt && \
    venv/bin/python3 ./codegen.py

RUN cmake .
RUN cmake --build .
