#define RPC_cuGetErrorString 0
#define RPC_cuGetErrorName 1
#define RPC_cuInit 2
#define RPC_cuDriverGetVersion 3
#define RPC_cuDeviceGet 4
#define RPC_cuDeviceGetCount 5
#define RPC_cuDeviceGetName 6
#define RPC_cuDeviceGetUuid_v2 7
#define RPC_cuDeviceGetLuid 8
#define RPC_cuDeviceTotalMem_v2 9
#define RPC_cuDeviceGetTexture1DLinearMaxWidth 10
#define RPC_cuDeviceGetAttribute 11
#define RPC_cuDeviceGetNvSciSyncAttributes 12
#define RPC_cuDeviceSetMemPool 13
#define RPC_cuDeviceGetMemPool 14
#define RPC_cuDeviceGetDefaultMemPool 15
#define RPC_cuDeviceGetExecAffinitySupport 16
#define RPC_cuFlushGPUDirectRDMAWrites 17
#define RPC_cuDeviceGetProperties 18
#define RPC_cuDeviceComputeCapability 19
#define RPC_cuDevicePrimaryCtxRetain 20
#define RPC_cuDevicePrimaryCtxRelease_v2 21
#define RPC_cuDevicePrimaryCtxSetFlags_v2 22
#define RPC_cuDevicePrimaryCtxGetState 23
#define RPC_cuDevicePrimaryCtxReset_v2 24
#define RPC_cuCtxDestroy_v2 25
#define RPC_cuCtxPushCurrent_v2 26
#define RPC_cuCtxPopCurrent_v2 27
#define RPC_cuCtxSetCurrent 28
#define RPC_cuCtxGetCurrent 29
#define RPC_cuCtxGetDevice 30
#define RPC_cuCtxGetFlags 31
#define RPC_cuCtxGetId 32
#define RPC_cuCtxSynchronize 33
#define RPC_cuCtxSetLimit 34
#define RPC_cuCtxGetLimit 35
#define RPC_cuCtxGetCacheConfig 36
#define RPC_cuCtxSetCacheConfig 37
#define RPC_cuCtxGetApiVersion 38
#define RPC_cuCtxGetStreamPriorityRange 39
#define RPC_cuCtxResetPersistingL2Cache 40
#define RPC_cuCtxGetExecAffinity 41
#define RPC_cuCtxAttach 42
#define RPC_cuCtxDetach 43
#define RPC_cuCtxGetSharedMemConfig 44
#define RPC_cuCtxSetSharedMemConfig 45
#define RPC_cuModuleLoad 46
#define RPC_cuModuleLoadData 47
#define RPC_cuModuleLoadDataEx 48
#define RPC_cuModuleLoadFatBinary 49
#define RPC_cuModuleUnload 50
#define RPC_cuModuleGetLoadingMode 51
#define RPC_cuModuleGetFunction 52
#define RPC_cuModuleGetGlobal_v2 53
#define RPC_cuLinkCreate_v2 54
#define RPC_cuLinkAddFile_v2 55
#define RPC_cuLinkComplete 56
#define RPC_cuLinkDestroy 57
#define RPC_cuModuleGetTexRef 58
#define RPC_cuModuleGetSurfRef 59
#define RPC_cuLibraryLoadData 60
#define RPC_cuLibraryLoadFromFile 61
#define RPC_cuLibraryUnload 62
#define RPC_cuLibraryGetKernel 63
#define RPC_cuLibraryGetModule 64
#define RPC_cuKernelGetFunction 65
#define RPC_cuLibraryGetGlobal 66
#define RPC_cuLibraryGetManaged 67
#define RPC_cuLibraryGetUnifiedFunction 68
#define RPC_cuKernelGetAttribute 69
#define RPC_cuKernelSetAttribute 70
#define RPC_cuKernelSetCacheConfig 71
#define RPC_cuMemGetInfo_v2 72
#define RPC_cuMemAlloc_v2 73
#define RPC_cuMemAllocPitch_v2 74
#define RPC_cuMemFree_v2 75
#define RPC_cuMemGetAddressRange_v2 76
#define RPC_cuMemAllocHost_v2 77
#define RPC_cuMemFreeHost 78
#define RPC_cuMemHostAlloc 79
#define RPC_cuMemHostGetDevicePointer_v2 80
#define RPC_cuMemHostGetFlags 81
#define RPC_cuMemAllocManaged 82
#define RPC_cuDeviceGetByPCIBusId 83
#define RPC_cuDeviceGetPCIBusId 84
#define RPC_cuIpcGetEventHandle 85
#define RPC_cuIpcOpenEventHandle 86
#define RPC_cuIpcGetMemHandle 87
#define RPC_cuIpcOpenMemHandle_v2 88
#define RPC_cuIpcCloseMemHandle 89
#define RPC_cuMemcpy 90
#define RPC_cuMemcpyPeer 91
#define RPC_cuMemcpyHtoD_v2 92
#define RPC_cuMemcpyDtoH_v2 93
#define RPC_cuMemcpyDtoD_v2 94
#define RPC_cuMemcpyDtoA_v2 95
#define RPC_cuMemcpyAtoD_v2 96
#define RPC_cuMemcpyHtoA_v2 97
#define RPC_cuMemcpyAtoH_v2 98
#define RPC_cuMemcpyAtoA_v2 99
#define RPC_cuMemcpy2D_v2 100
#define RPC_cuMemcpy2DUnaligned_v2 101
#define RPC_cuMemcpy3D_v2 102
#define RPC_cuMemcpy3DPeer 103
#define RPC_cuMemcpyAsync 104
#define RPC_cuMemcpyPeerAsync 105
#define RPC_cuMemcpyHtoDAsync_v2 106
#define RPC_cuMemcpyDtoHAsync_v2 107
#define RPC_cuMemcpyDtoDAsync_v2 108
#define RPC_cuMemcpyHtoAAsync_v2 109
#define RPC_cuMemcpy2DAsync_v2 110
#define RPC_cuMemcpy3DAsync_v2 111
#define RPC_cuMemcpy3DPeerAsync 112
#define RPC_cuMemsetD8_v2 113
#define RPC_cuMemsetD16_v2 114
#define RPC_cuMemsetD32_v2 115
#define RPC_cuMemsetD2D8_v2 116
#define RPC_cuMemsetD2D16_v2 117
#define RPC_cuMemsetD2D32_v2 118
#define RPC_cuMemsetD8Async 119
#define RPC_cuMemsetD16Async 120
#define RPC_cuMemsetD32Async 121
#define RPC_cuMemsetD2D8Async 122
#define RPC_cuMemsetD2D16Async 123
#define RPC_cuMemsetD2D32Async 124
#define RPC_cuArrayCreate_v2 125
#define RPC_cuArrayGetDescriptor_v2 126
#define RPC_cuArrayGetSparseProperties 127
#define RPC_cuMipmappedArrayGetSparseProperties 128
#define RPC_cuArrayGetMemoryRequirements 129
#define RPC_cuMipmappedArrayGetMemoryRequirements 130
#define RPC_cuArrayGetPlane 131
#define RPC_cuArrayDestroy 132
#define RPC_cuArray3DCreate_v2 133
#define RPC_cuArray3DGetDescriptor_v2 134
#define RPC_cuMipmappedArrayCreate 135
#define RPC_cuMipmappedArrayGetLevel 136
#define RPC_cuMipmappedArrayDestroy 137
#define RPC_cuMemAddressReserve 138
#define RPC_cuMemAddressFree 139
#define RPC_cuMemCreate 140
#define RPC_cuMemRelease 141
#define RPC_cuMemMap 142
#define RPC_cuMemMapArrayAsync 143
#define RPC_cuMemUnmap 144
#define RPC_cuMemSetAccess 145
#define RPC_cuMemGetAccess 146
#define RPC_cuMemGetAllocationGranularity 147
#define RPC_cuMemGetAllocationPropertiesFromHandle 148
#define RPC_cuMemFreeAsync 149
#define RPC_cuMemAllocAsync 150
#define RPC_cuMemPoolTrimTo 151
#define RPC_cuMemPoolSetAccess 152
#define RPC_cuMemPoolGetAccess 153
#define RPC_cuMemPoolCreate 154
#define RPC_cuMemPoolDestroy 155
#define RPC_cuMemAllocFromPoolAsync 156
#define RPC_cuMemPoolExportPointer 157
#define RPC_cuMemPoolImportPointer 158
#define RPC_cuMemRangeGetAttributes 159
#define RPC_cuPointerSetAttribute 160
#define RPC_cuPointerGetAttributes 161
#define RPC_cuStreamCreate 162
#define RPC_cuStreamCreateWithPriority 163
#define RPC_cuStreamGetPriority 164
#define RPC_cuStreamGetFlags 165
#define RPC_cuStreamGetId 166
#define RPC_cuStreamGetCtx 167
#define RPC_cuStreamWaitEvent 168
#define RPC_cuStreamBeginCapture_v2 169
#define RPC_cuThreadExchangeStreamCaptureMode 170
#define RPC_cuStreamEndCapture 171
#define RPC_cuStreamIsCapturing 172
#define RPC_cuStreamAttachMemAsync 173
#define RPC_cuStreamQuery 174
#define RPC_cuStreamSynchronize 175
#define RPC_cuStreamDestroy_v2 176
#define RPC_cuStreamCopyAttributes 177
#define RPC_cuStreamGetAttribute 178
#define RPC_cuStreamSetAttribute 179
#define RPC_cuEventCreate 180
#define RPC_cuEventRecord 181
#define RPC_cuEventRecordWithFlags 182
#define RPC_cuEventQuery 183
#define RPC_cuEventSynchronize 184
#define RPC_cuEventDestroy_v2 185
#define RPC_cuEventElapsedTime_v2 186
#define RPC_cuImportExternalMemory 187
#define RPC_cuExternalMemoryGetMappedBuffer 188
#define RPC_cuExternalMemoryGetMappedMipmappedArray 189
#define RPC_cuDestroyExternalMemory 190
#define RPC_cuImportExternalSemaphore 191
#define RPC_cuSignalExternalSemaphoresAsync 192
#define RPC_cuWaitExternalSemaphoresAsync 193
#define RPC_cuDestroyExternalSemaphore 194
#define RPC_cuStreamWaitValue32_v2 195
#define RPC_cuStreamWaitValue64_v2 196
#define RPC_cuStreamWriteValue32_v2 197
#define RPC_cuStreamWriteValue64_v2 198
#define RPC_cuStreamBatchMemOp_v2 199
#define RPC_cuFuncGetAttribute 200
#define RPC_cuFuncSetAttribute 201
#define RPC_cuFuncSetCacheConfig 202
#define RPC_cuFuncGetModule 203
#define RPC_cuLaunchKernel 204
#define RPC_cuLaunchKernelEx 205
#define RPC_cuLaunchCooperativeKernel 206
#define RPC_cuLaunchCooperativeKernelMultiDevice 207
#define RPC_cuLaunchHostFunc 208
#define RPC_cuFuncSetBlockShape 209
#define RPC_cuFuncSetSharedSize 210
#define RPC_cuParamSetSize 211
#define RPC_cuParamSeti 212
#define RPC_cuParamSetf 213
#define RPC_cuLaunch 214
#define RPC_cuLaunchGrid 215
#define RPC_cuLaunchGridAsync 216
#define RPC_cuParamSetTexRef 217
#define RPC_cuFuncSetSharedMemConfig 218
#define RPC_cuGraphCreate 219
#define RPC_cuGraphAddKernelNode_v2 220
#define RPC_cuGraphKernelNodeGetParams_v2 221
#define RPC_cuGraphKernelNodeSetParams_v2 222
#define RPC_cuGraphAddMemcpyNode 223
#define RPC_cuGraphMemcpyNodeGetParams 224
#define RPC_cuGraphMemcpyNodeSetParams 225
#define RPC_cuGraphAddMemsetNode 226
#define RPC_cuGraphMemsetNodeGetParams 227
#define RPC_cuGraphMemsetNodeSetParams 228
#define RPC_cuGraphAddHostNode 229
#define RPC_cuGraphHostNodeGetParams 230
#define RPC_cuGraphHostNodeSetParams 231
#define RPC_cuGraphAddChildGraphNode 232
#define RPC_cuGraphChildGraphNodeGetGraph 233
#define RPC_cuGraphAddEmptyNode 234
#define RPC_cuGraphAddEventRecordNode 235
#define RPC_cuGraphEventRecordNodeGetEvent 236
#define RPC_cuGraphEventRecordNodeSetEvent 237
#define RPC_cuGraphAddEventWaitNode 238
#define RPC_cuGraphEventWaitNodeGetEvent 239
#define RPC_cuGraphEventWaitNodeSetEvent 240
#define RPC_cuGraphAddExternalSemaphoresSignalNode 241
#define RPC_cuGraphExternalSemaphoresSignalNodeGetParams 242
#define RPC_cuGraphExternalSemaphoresSignalNodeSetParams 243
#define RPC_cuGraphAddExternalSemaphoresWaitNode 244
#define RPC_cuGraphExternalSemaphoresWaitNodeGetParams 245
#define RPC_cuGraphExternalSemaphoresWaitNodeSetParams 246
#define RPC_cuGraphAddBatchMemOpNode 247
#define RPC_cuGraphBatchMemOpNodeGetParams 248
#define RPC_cuGraphBatchMemOpNodeSetParams 249
#define RPC_cuGraphExecBatchMemOpNodeSetParams 250
#define RPC_cuGraphAddMemAllocNode 251
#define RPC_cuGraphMemAllocNodeGetParams 252
#define RPC_cuGraphAddMemFreeNode 253
#define RPC_cuGraphMemFreeNodeGetParams 254
#define RPC_cuDeviceGraphMemTrim 255
#define RPC_cuGraphClone 256
#define RPC_cuGraphNodeFindInClone 257
#define RPC_cuGraphNodeGetType 258
#define RPC_cuGraphGetNodes 259
#define RPC_cuGraphGetRootNodes 260
#define RPC_cuGraphDestroyNode 261
#define RPC_cuGraphInstantiateWithFlags 262
#define RPC_cuGraphInstantiateWithParams 263
#define RPC_cuGraphExecGetFlags 264
#define RPC_cuGraphExecKernelNodeSetParams_v2 265
#define RPC_cuGraphExecMemcpyNodeSetParams 266
#define RPC_cuGraphExecMemsetNodeSetParams 267
#define RPC_cuGraphExecHostNodeSetParams 268
#define RPC_cuGraphExecChildGraphNodeSetParams 269
#define RPC_cuGraphExecEventRecordNodeSetEvent 270
#define RPC_cuGraphExecEventWaitNodeSetEvent 271
#define RPC_cuGraphExecExternalSemaphoresSignalNodeSetParams 272
#define RPC_cuGraphExecExternalSemaphoresWaitNodeSetParams 273
#define RPC_cuGraphNodeSetEnabled 274
#define RPC_cuGraphNodeGetEnabled 275
#define RPC_cuGraphUpload 276
#define RPC_cuGraphLaunch 277
#define RPC_cuGraphExecDestroy 278
#define RPC_cuGraphDestroy 279
#define RPC_cuGraphExecUpdate_v2 280
#define RPC_cuGraphKernelNodeCopyAttributes 281
#define RPC_cuGraphKernelNodeGetAttribute 282
#define RPC_cuGraphKernelNodeSetAttribute 283
#define RPC_cuGraphDebugDotPrint 284
#define RPC_cuUserObjectRetain 285
#define RPC_cuUserObjectRelease 286
#define RPC_cuGraphRetainUserObject 287
#define RPC_cuGraphReleaseUserObject 288
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessor 289
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags 290
#define RPC_cuOccupancyMaxPotentialBlockSize 291
#define RPC_cuOccupancyMaxPotentialBlockSizeWithFlags 292
#define RPC_cuOccupancyAvailableDynamicSMemPerBlock 293
#define RPC_cuOccupancyMaxPotentialClusterSize 294
#define RPC_cuOccupancyMaxActiveClusters 295
#define RPC_cuTexRefSetArray 296
#define RPC_cuTexRefSetMipmappedArray 297
#define RPC_cuTexRefSetAddress_v2 298
#define RPC_cuTexRefSetAddress2D_v3 299
#define RPC_cuTexRefSetFormat 300
#define RPC_cuTexRefSetAddressMode 301
#define RPC_cuTexRefSetFilterMode 302
#define RPC_cuTexRefSetMipmapFilterMode 303
#define RPC_cuTexRefSetMipmapLevelBias 304
#define RPC_cuTexRefSetMipmapLevelClamp 305
#define RPC_cuTexRefSetMaxAnisotropy 306
#define RPC_cuTexRefSetBorderColor 307
#define RPC_cuTexRefSetFlags 308
#define RPC_cuTexRefGetAddress_v2 309
#define RPC_cuTexRefGetArray 310
#define RPC_cuTexRefGetMipmappedArray 311
#define RPC_cuTexRefGetAddressMode 312
#define RPC_cuTexRefGetFilterMode 313
#define RPC_cuTexRefGetFormat 314
#define RPC_cuTexRefGetMipmapFilterMode 315
#define RPC_cuTexRefGetMipmapLevelBias 316
#define RPC_cuTexRefGetMipmapLevelClamp 317
#define RPC_cuTexRefGetMaxAnisotropy 318
#define RPC_cuTexRefGetBorderColor 319
#define RPC_cuTexRefGetFlags 320
#define RPC_cuTexRefCreate 321
#define RPC_cuTexRefDestroy 322
#define RPC_cuSurfRefSetArray 323
#define RPC_cuSurfRefGetArray 324
#define RPC_cuTexObjectCreate 325
#define RPC_cuTexObjectDestroy 326
#define RPC_cuTexObjectGetResourceDesc 327
#define RPC_cuTexObjectGetTextureDesc 328
#define RPC_cuTexObjectGetResourceViewDesc 329
#define RPC_cuSurfObjectCreate 330
#define RPC_cuSurfObjectDestroy 331
#define RPC_cuSurfObjectGetResourceDesc 332
#define RPC_cuDeviceCanAccessPeer 333
#define RPC_cuCtxEnablePeerAccess 334
#define RPC_cuCtxDisablePeerAccess 335
#define RPC_cuDeviceGetP2PAttribute 336
#define RPC_cuGraphicsUnregisterResource 337
#define RPC_cuGraphicsSubResourceGetMappedArray 338
#define RPC_cuGraphicsResourceGetMappedMipmappedArray 339
#define RPC_cuGraphicsResourceGetMappedPointer_v2 340
#define RPC_cuGraphicsResourceSetMapFlags_v2 341
#define RPC_cuGraphicsMapResources 342
#define RPC_cuGraphicsUnmapResources 343
#define RPC_cuGetProcAddress_v2 344
#define RPC_cuGetExportTable 345
