#define RPC_cuGetErrorString 0
#define RPC_cuGetErrorName 1
#define RPC_cuInit 2
#define RPC_cuDriverGetVersion 3
#define RPC_cuDeviceGet 4
#define RPC_cuDeviceGetCount 5
#define RPC_cuDeviceGetName 6
#define RPC_cuDeviceGetUuid_v2 7
#define RPC_cuDeviceGetLuid 8
#define RPC_cuDeviceTotalMem_v2 9
#define RPC_cuDeviceGetTexture1DLinearMaxWidth 10
#define RPC_cuDeviceGetAttribute 11
#define RPC_cuDeviceGetNvSciSyncAttributes 12
#define RPC_cuDeviceSetMemPool 13
#define RPC_cuDeviceGetMemPool 14
#define RPC_cuDeviceGetDefaultMemPool 15
#define RPC_cuDeviceGetExecAffinitySupport 16
#define RPC_cuFlushGPUDirectRDMAWrites 17
#define RPC_cuDeviceGetProperties 18
#define RPC_cuDeviceComputeCapability 19
#define RPC_cuDevicePrimaryCtxRetain 20
#define RPC_cuDevicePrimaryCtxRelease_v2 21
#define RPC_cuDevicePrimaryCtxSetFlags_v2 22
#define RPC_cuDevicePrimaryCtxGetState 23
#define RPC_cuDevicePrimaryCtxReset_v2 24
#define RPC_cuCtxDestroy_v2 25
#define RPC_cuCtxPushCurrent_v2 26
#define RPC_cuCtxPopCurrent_v2 27
#define RPC_cuCtxSetCurrent 28
#define RPC_cuCtxGetCurrent 29
#define RPC_cuCtxGetDevice 30
#define RPC_cuCtxGetFlags 31
#define RPC_cuCtxGetId 32
#define RPC_cuCtxSynchronize 33
#define RPC_cuCtxSetLimit 34
#define RPC_cuCtxGetLimit 35
#define RPC_cuCtxGetCacheConfig 36
#define RPC_cuCtxSetCacheConfig 37
#define RPC_cuCtxGetApiVersion 38
#define RPC_cuCtxGetStreamPriorityRange 39
#define RPC_cuCtxResetPersistingL2Cache 40
#define RPC_cuCtxGetExecAffinity 41
#define RPC_cuCtxAttach 42
#define RPC_cuCtxDetach 43
#define RPC_cuCtxGetSharedMemConfig 44
#define RPC_cuCtxSetSharedMemConfig 45
#define RPC_cuModuleLoad 46
#define RPC_cuModuleLoadData 47
#define RPC_cuModuleLoadDataEx 48
#define RPC_cuModuleLoadFatBinary 49
#define RPC_cuModuleUnload 50
#define RPC_cuModuleGetLoadingMode 51
#define RPC_cuModuleGetFunction 52
#define RPC_cuModuleGetGlobal_v2 53
#define RPC_cuLinkCreate_v2 54
#define RPC_cuLinkAddData_v2 55
#define RPC_cuLinkAddFile_v2 56
#define RPC_cuLinkComplete 57
#define RPC_cuLinkDestroy 58
#define RPC_cuModuleGetTexRef 59
#define RPC_cuModuleGetSurfRef 60
#define RPC_cuLibraryLoadData 61
#define RPC_cuLibraryLoadFromFile 62
#define RPC_cuLibraryUnload 63
#define RPC_cuLibraryGetKernel 64
#define RPC_cuLibraryGetModule 65
#define RPC_cuKernelGetFunction 66
#define RPC_cuLibraryGetGlobal 67
#define RPC_cuLibraryGetManaged 68
#define RPC_cuLibraryGetUnifiedFunction 69
#define RPC_cuKernelGetAttribute 70
#define RPC_cuKernelSetAttribute 71
#define RPC_cuKernelSetCacheConfig 72
#define RPC_cuMemGetInfo_v2 73
#define RPC_cuMemAlloc_v2 74
#define RPC_cuMemAllocPitch_v2 75
#define RPC_cuMemFree_v2 76
#define RPC_cuMemGetAddressRange_v2 77
#define RPC_cuMemAllocHost_v2 78
#define RPC_cuMemFreeHost 79
#define RPC_cuMemHostAlloc 80
#define RPC_cuMemHostGetDevicePointer_v2 81
#define RPC_cuMemHostGetFlags 82
#define RPC_cuMemAllocManaged 83
#define RPC_cuDeviceGetByPCIBusId 84
#define RPC_cuDeviceGetPCIBusId 85
#define RPC_cuIpcGetEventHandle 86
#define RPC_cuIpcOpenEventHandle 87
#define RPC_cuIpcGetMemHandle 88
#define RPC_cuIpcOpenMemHandle_v2 89
#define RPC_cuIpcCloseMemHandle 90
#define RPC_cuMemcpy 91
#define RPC_cuMemcpyPeer 92
#define RPC_cuMemcpyHtoD_v2 93
#define RPC_cuMemcpyDtoH_v2 94
#define RPC_cuMemcpyDtoD_v2 95
#define RPC_cuMemcpyDtoA_v2 96
#define RPC_cuMemcpyAtoD_v2 97
#define RPC_cuMemcpyHtoA_v2 98
#define RPC_cuMemcpyAtoH_v2 99
#define RPC_cuMemcpyAtoA_v2 100
#define RPC_cuMemcpy2D_v2 101
#define RPC_cuMemcpy2DUnaligned_v2 102
#define RPC_cuMemcpy3D_v2 103
#define RPC_cuMemcpy3DPeer 104
#define RPC_cuMemcpyAsync 105
#define RPC_cuMemcpyPeerAsync 106
#define RPC_cuMemcpyHtoDAsync_v2 107
#define RPC_cuMemcpyDtoHAsync_v2 108
#define RPC_cuMemcpyDtoDAsync_v2 109
#define RPC_cuMemcpyHtoAAsync_v2 110
#define RPC_cuMemcpy2DAsync_v2 111
#define RPC_cuMemcpy3DAsync_v2 112
#define RPC_cuMemcpy3DPeerAsync 113
#define RPC_cuMemsetD8_v2 114
#define RPC_cuMemsetD16_v2 115
#define RPC_cuMemsetD32_v2 116
#define RPC_cuMemsetD2D8_v2 117
#define RPC_cuMemsetD2D16_v2 118
#define RPC_cuMemsetD2D32_v2 119
#define RPC_cuMemsetD8Async 120
#define RPC_cuMemsetD16Async 121
#define RPC_cuMemsetD32Async 122
#define RPC_cuMemsetD2D8Async 123
#define RPC_cuMemsetD2D16Async 124
#define RPC_cuMemsetD2D32Async 125
#define RPC_cuArrayCreate_v2 126
#define RPC_cuArrayGetDescriptor_v2 127
#define RPC_cuArrayGetSparseProperties 128
#define RPC_cuMipmappedArrayGetSparseProperties 129
#define RPC_cuArrayGetMemoryRequirements 130
#define RPC_cuMipmappedArrayGetMemoryRequirements 131
#define RPC_cuArrayGetPlane 132
#define RPC_cuArrayDestroy 133
#define RPC_cuArray3DCreate_v2 134
#define RPC_cuArray3DGetDescriptor_v2 135
#define RPC_cuMipmappedArrayCreate 136
#define RPC_cuMipmappedArrayGetLevel 137
#define RPC_cuMipmappedArrayDestroy 138
#define RPC_cuMemAddressReserve 139
#define RPC_cuMemAddressFree 140
#define RPC_cuMemCreate 141
#define RPC_cuMemRelease 142
#define RPC_cuMemMap 143
#define RPC_cuMemMapArrayAsync 144
#define RPC_cuMemUnmap 145
#define RPC_cuMemSetAccess 146
#define RPC_cuMemGetAccess 147
#define RPC_cuMemGetAllocationGranularity 148
#define RPC_cuMemGetAllocationPropertiesFromHandle 149
#define RPC_cuMemFreeAsync 150
#define RPC_cuMemAllocAsync 151
#define RPC_cuMemPoolTrimTo 152
#define RPC_cuMemPoolSetAccess 153
#define RPC_cuMemPoolGetAccess 154
#define RPC_cuMemPoolCreate 155
#define RPC_cuMemPoolDestroy 156
#define RPC_cuMemAllocFromPoolAsync 157
#define RPC_cuMemPoolExportPointer 158
#define RPC_cuMemPoolImportPointer 159
#define RPC_cuMemRangeGetAttributes 160
#define RPC_cuPointerSetAttribute 161
#define RPC_cuPointerGetAttributes 162
#define RPC_cuStreamCreate 163
#define RPC_cuStreamCreateWithPriority 164
#define RPC_cuStreamGetPriority 165
#define RPC_cuStreamGetFlags 166
#define RPC_cuStreamGetId 167
#define RPC_cuStreamGetCtx 168
#define RPC_cuStreamWaitEvent 169
#define RPC_cuStreamBeginCapture_v2 170
#define RPC_cuThreadExchangeStreamCaptureMode 171
#define RPC_cuStreamEndCapture 172
#define RPC_cuStreamIsCapturing 173
#define RPC_cuStreamAttachMemAsync 174
#define RPC_cuStreamQuery 175
#define RPC_cuStreamSynchronize 176
#define RPC_cuStreamDestroy_v2 177
#define RPC_cuStreamCopyAttributes 178
#define RPC_cuStreamGetAttribute 179
#define RPC_cuStreamSetAttribute 180
#define RPC_cuEventCreate 181
#define RPC_cuEventRecord 182
#define RPC_cuEventRecordWithFlags 183
#define RPC_cuEventQuery 184
#define RPC_cuEventSynchronize 185
#define RPC_cuEventDestroy_v2 186
#define RPC_cuEventElapsedTime_v2 187
#define RPC_cuImportExternalMemory 188
#define RPC_cuExternalMemoryGetMappedBuffer 189
#define RPC_cuExternalMemoryGetMappedMipmappedArray 190
#define RPC_cuDestroyExternalMemory 191
#define RPC_cuImportExternalSemaphore 192
#define RPC_cuSignalExternalSemaphoresAsync 193
#define RPC_cuWaitExternalSemaphoresAsync 194
#define RPC_cuDestroyExternalSemaphore 195
#define RPC_cuStreamWaitValue32_v2 196
#define RPC_cuStreamWaitValue64_v2 197
#define RPC_cuStreamWriteValue32_v2 198
#define RPC_cuStreamWriteValue64_v2 199
#define RPC_cuStreamBatchMemOp_v2 200
#define RPC_cuFuncGetAttribute 201
#define RPC_cuFuncSetAttribute 202
#define RPC_cuFuncSetCacheConfig 203
#define RPC_cuFuncGetModule 204
#define RPC_cuLaunchKernel 205
#define RPC_cuLaunchKernelEx 206
#define RPC_cuLaunchCooperativeKernel 207
#define RPC_cuLaunchCooperativeKernelMultiDevice 208
#define RPC_cuLaunchHostFunc 209
#define RPC_cuFuncSetBlockShape 210
#define RPC_cuFuncSetSharedSize 211
#define RPC_cuParamSetSize 212
#define RPC_cuParamSeti 213
#define RPC_cuParamSetf 214
#define RPC_cuLaunch 215
#define RPC_cuLaunchGrid 216
#define RPC_cuLaunchGridAsync 217
#define RPC_cuParamSetTexRef 218
#define RPC_cuFuncSetSharedMemConfig 219
#define RPC_cuGraphCreate 220
#define RPC_cuGraphAddKernelNode_v2 221
#define RPC_cuGraphKernelNodeGetParams_v2 222
#define RPC_cuGraphKernelNodeSetParams_v2 223
#define RPC_cuGraphAddMemcpyNode 224
#define RPC_cuGraphMemcpyNodeGetParams 225
#define RPC_cuGraphMemcpyNodeSetParams 226
#define RPC_cuGraphAddMemsetNode 227
#define RPC_cuGraphMemsetNodeGetParams 228
#define RPC_cuGraphMemsetNodeSetParams 229
#define RPC_cuGraphAddHostNode 230
#define RPC_cuGraphHostNodeGetParams 231
#define RPC_cuGraphHostNodeSetParams 232
#define RPC_cuGraphAddChildGraphNode 233
#define RPC_cuGraphChildGraphNodeGetGraph 234
#define RPC_cuGraphAddEmptyNode 235
#define RPC_cuGraphAddEventRecordNode 236
#define RPC_cuGraphEventRecordNodeGetEvent 237
#define RPC_cuGraphEventRecordNodeSetEvent 238
#define RPC_cuGraphAddEventWaitNode 239
#define RPC_cuGraphEventWaitNodeGetEvent 240
#define RPC_cuGraphEventWaitNodeSetEvent 241
#define RPC_cuGraphAddExternalSemaphoresSignalNode 242
#define RPC_cuGraphExternalSemaphoresSignalNodeGetParams 243
#define RPC_cuGraphExternalSemaphoresSignalNodeSetParams 244
#define RPC_cuGraphAddExternalSemaphoresWaitNode 245
#define RPC_cuGraphExternalSemaphoresWaitNodeGetParams 246
#define RPC_cuGraphExternalSemaphoresWaitNodeSetParams 247
#define RPC_cuGraphAddBatchMemOpNode 248
#define RPC_cuGraphBatchMemOpNodeGetParams 249
#define RPC_cuGraphBatchMemOpNodeSetParams 250
#define RPC_cuGraphExecBatchMemOpNodeSetParams 251
#define RPC_cuGraphAddMemAllocNode 252
#define RPC_cuGraphMemAllocNodeGetParams 253
#define RPC_cuGraphAddMemFreeNode 254
#define RPC_cuGraphMemFreeNodeGetParams 255
#define RPC_cuDeviceGraphMemTrim 256
#define RPC_cuGraphClone 257
#define RPC_cuGraphNodeFindInClone 258
#define RPC_cuGraphNodeGetType 259
#define RPC_cuGraphGetNodes 260
#define RPC_cuGraphGetRootNodes 261
#define RPC_cuGraphDestroyNode 262
#define RPC_cuGraphInstantiateWithFlags 263
#define RPC_cuGraphInstantiateWithParams 264
#define RPC_cuGraphExecGetFlags 265
#define RPC_cuGraphExecKernelNodeSetParams_v2 266
#define RPC_cuGraphExecMemcpyNodeSetParams 267
#define RPC_cuGraphExecMemsetNodeSetParams 268
#define RPC_cuGraphExecHostNodeSetParams 269
#define RPC_cuGraphExecChildGraphNodeSetParams 270
#define RPC_cuGraphExecEventRecordNodeSetEvent 271
#define RPC_cuGraphExecEventWaitNodeSetEvent 272
#define RPC_cuGraphExecExternalSemaphoresSignalNodeSetParams 273
#define RPC_cuGraphExecExternalSemaphoresWaitNodeSetParams 274
#define RPC_cuGraphNodeSetEnabled 275
#define RPC_cuGraphNodeGetEnabled 276
#define RPC_cuGraphUpload 277
#define RPC_cuGraphLaunch 278
#define RPC_cuGraphExecDestroy 279
#define RPC_cuGraphDestroy 280
#define RPC_cuGraphExecUpdate_v2 281
#define RPC_cuGraphKernelNodeCopyAttributes 282
#define RPC_cuGraphKernelNodeGetAttribute 283
#define RPC_cuGraphKernelNodeSetAttribute 284
#define RPC_cuGraphDebugDotPrint 285
#define RPC_cuUserObjectRetain 286
#define RPC_cuUserObjectRelease 287
#define RPC_cuGraphRetainUserObject 288
#define RPC_cuGraphReleaseUserObject 289
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessor 290
#define RPC_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags 291
#define RPC_cuOccupancyMaxPotentialBlockSize 292
#define RPC_cuOccupancyMaxPotentialBlockSizeWithFlags 293
#define RPC_cuOccupancyAvailableDynamicSMemPerBlock 294
#define RPC_cuOccupancyMaxPotentialClusterSize 295
#define RPC_cuOccupancyMaxActiveClusters 296
#define RPC_cuTexRefSetArray 297
#define RPC_cuTexRefSetMipmappedArray 298
#define RPC_cuTexRefSetAddress_v2 299
#define RPC_cuTexRefSetAddress2D_v3 300
#define RPC_cuTexRefSetFormat 301
#define RPC_cuTexRefSetAddressMode 302
#define RPC_cuTexRefSetFilterMode 303
#define RPC_cuTexRefSetMipmapFilterMode 304
#define RPC_cuTexRefSetMipmapLevelBias 305
#define RPC_cuTexRefSetMipmapLevelClamp 306
#define RPC_cuTexRefSetMaxAnisotropy 307
#define RPC_cuTexRefSetBorderColor 308
#define RPC_cuTexRefSetFlags 309
#define RPC_cuTexRefGetAddress_v2 310
#define RPC_cuTexRefGetArray 311
#define RPC_cuTexRefGetMipmappedArray 312
#define RPC_cuTexRefGetAddressMode 313
#define RPC_cuTexRefGetFilterMode 314
#define RPC_cuTexRefGetFormat 315
#define RPC_cuTexRefGetMipmapFilterMode 316
#define RPC_cuTexRefGetMipmapLevelBias 317
#define RPC_cuTexRefGetMipmapLevelClamp 318
#define RPC_cuTexRefGetMaxAnisotropy 319
#define RPC_cuTexRefGetBorderColor 320
#define RPC_cuTexRefGetFlags 321
#define RPC_cuTexRefCreate 322
#define RPC_cuTexRefDestroy 323
#define RPC_cuSurfRefSetArray 324
#define RPC_cuSurfRefGetArray 325
#define RPC_cuTexObjectCreate 326
#define RPC_cuTexObjectDestroy 327
#define RPC_cuTexObjectGetResourceDesc 328
#define RPC_cuTexObjectGetTextureDesc 329
#define RPC_cuTexObjectGetResourceViewDesc 330
#define RPC_cuSurfObjectCreate 331
#define RPC_cuSurfObjectDestroy 332
#define RPC_cuSurfObjectGetResourceDesc 333
#define RPC_cuDeviceCanAccessPeer 334
#define RPC_cuCtxEnablePeerAccess 335
#define RPC_cuCtxDisablePeerAccess 336
#define RPC_cuDeviceGetP2PAttribute 337
#define RPC_cuGraphicsUnregisterResource 338
#define RPC_cuGraphicsSubResourceGetMappedArray 339
#define RPC_cuGraphicsResourceGetMappedMipmappedArray 340
#define RPC_cuGraphicsResourceGetMappedPointer_v2 341
#define RPC_cuGraphicsResourceSetMapFlags_v2 342
#define RPC_cuGraphicsMapResources 343
#define RPC_cuGraphicsUnmapResources 344
#define RPC_cuGetProcAddress_v2 345
#define RPC_cuGetExportTable 346
#define RPC_nvmlInit_v2 347
#define RPC_nvmlInitWithFlags 348
#define RPC_nvmlShutdown 349
#define RPC_nvmlSystemGetDriverVersion 350
#define RPC_nvmlSystemGetNVMLVersion 351
#define RPC_nvmlSystemGetCudaDriverVersion 352
#define RPC_nvmlSystemGetCudaDriverVersion_v2 353
#define RPC_nvmlDeviceGetCount_v2 354
#define RPC_nvmlDeviceGetHandleByIndex_v2 355
#define RPC_nvmlDeviceGetHandleByUUID 356
#define RPC_nvmlDeviceGetHandleByPciBusId_v2 357
#define RPC_nvmlDeviceGetName 358
#define RPC_nvmlDeviceGetUUID 359
#define RPC_nvmlDeviceGetIndex 360
#define RPC_nvmlDeviceGetMinorNumber 361
#define RPC_nvmlDeviceGetPciInfo_v3 362
#define RPC_nvmlDeviceGetMemoryInfo 363
#define RPC_nvmlDeviceGetUtilizationRates 364
#define RPC_nvmlDeviceGetTemperature 365
#define RPC_nvmlDeviceGetPowerUsage 366
#define RPC_nvmlDeviceGetPowerManagementLimit 367
#define RPC_nvmlDeviceGetClockInfo 368
#define RPC_nvmlDeviceGetMaxClockInfo 369
#define RPC_nvmlDeviceGetPerformanceState 370
#define RPC_nvmlDeviceGetComputeMode 371
#define RPC_nvmlDeviceGetPersistenceMode 372
#define RPC_nvmlDeviceGetFanSpeed 373
#define RPC_nvmlDeviceGetBrand 374
#define RPC_nvmlDeviceGetVbiosVersion 375
#define RPC_nvmlDeviceGetSerial 376
#define RPC_nvmlDeviceGetBoardPartNumber 377
#define RPC_nvmlDeviceGetDisplayMode 378
#define RPC_nvmlDeviceGetDisplayActive 379
#define RPC_nvmlDeviceGetCurrPcieLinkGeneration 380
#define RPC_nvmlDeviceGetCurrPcieLinkWidth 381
#define RPC_nvmlDeviceGetMaxPcieLinkGeneration 382
#define RPC_nvmlDeviceGetMaxPcieLinkWidth 383
#define RPC_nvmlDeviceGetPcieThroughput 384
#define RPC_nvmlDeviceGetPcieReplayCounter 385
#define RPC_nvmlDeviceGetComputeRunningProcesses 386
#define RPC_nvmlDeviceGetComputeRunningProcesses_v2 387
#define RPC_nvmlDeviceGetGraphicsRunningProcesses 388
#define RPC_nvmlDeviceGetGraphicsRunningProcesses_v2 389
#define RPC_nvmlDeviceGetMPSComputeRunningProcesses 390
#define RPC_nvmlDeviceGetMPSComputeRunningProcesses_v2 391
#define RPC_nvmlEventSetCreate 392
#define RPC_nvmlEventSetFree 393
#define RPC_nvmlEventSetWait_v2 394
#define RPC_nvmlDeviceRegisterEvents 395
#define RPC_nvmlDeviceGetMaxMigDeviceCount 396
#define RPC_nvmlDeviceGetEccMode 397
#define RPC_nvmlDeviceGetTemperatureV 398
#define RPC_nvmlDeviceGetEnforcedPowerLimit 399
#define RPC_nvmlDeviceGetMemoryInfo_v2 400
#define RPC_nvmlDeviceGetMigMode 401
#define RPC_nvmlDeviceGetVirtualizationMode 402
#define RPC_nvmlDeviceIsMigDeviceHandle 403
#define RPC_nvmlDeviceGetNvLinkRemoteDeviceType 404
#define RPC_nvmlDeviceGetNvLinkRemotePciInfo_v2 405
