#define RPC___cudaRegisterVar 0
#define RPC___cudaRegisterFunction 1
#define RPC___cudaRegisterFatBinary 2
#define RPC___cudaRegisterFatBinaryEnd 3
#define RPC___cudaPushCallConfiguration 4
#define RPC___cudaPopCallConfiguration 5
#define RPC_nvmlInit_v2 6
#define RPC_nvmlInitWithFlags 7
#define RPC_nvmlShutdown 8
#define RPC_nvmlErrorString 9
#define RPC_nvmlSystemGetDriverVersion 10
#define RPC_nvmlSystemGetNVMLVersion 11
#define RPC_nvmlSystemGetCudaDriverVersion 12
#define RPC_nvmlSystemGetCudaDriverVersion_v2 13
#define RPC_nvmlSystemGetProcessName 14
#define RPC_nvmlUnitGetCount 15
#define RPC_nvmlUnitGetHandleByIndex 16
#define RPC_nvmlUnitGetUnitInfo 17
#define RPC_nvmlUnitGetLedState 18
#define RPC_nvmlUnitGetPsuInfo 19
#define RPC_nvmlUnitGetTemperature 20
#define RPC_nvmlUnitGetFanSpeedInfo 21
#define RPC_nvmlUnitGetDevices 22
#define RPC_nvmlSystemGetHicVersion 23
#define RPC_nvmlDeviceGetCount_v2 24
#define RPC_nvmlDeviceGetAttributes_v2 25
#define RPC_nvmlDeviceGetHandleByIndex_v2 26
#define RPC_nvmlDeviceGetHandleBySerial 27
#define RPC_nvmlDeviceGetHandleByUUID 28
#define RPC_nvmlDeviceGetHandleByPciBusId_v2 29
#define RPC_nvmlDeviceGetName 30
#define RPC_nvmlDeviceGetBrand 31
#define RPC_nvmlDeviceGetIndex 32
#define RPC_nvmlDeviceGetSerial 33
#define RPC_nvmlDeviceGetMemoryAffinity 34
#define RPC_nvmlDeviceGetCpuAffinityWithinScope 35
#define RPC_nvmlDeviceGetCpuAffinity 36
#define RPC_nvmlDeviceSetCpuAffinity 37
#define RPC_nvmlDeviceClearCpuAffinity 38
#define RPC_nvmlDeviceGetTopologyCommonAncestor 39
#define RPC_nvmlDeviceGetTopologyNearestGpus 40
#define RPC_nvmlSystemGetTopologyGpuSet 41
#define RPC_nvmlDeviceGetP2PStatus 42
#define RPC_nvmlDeviceGetUUID 43
#define RPC_nvmlVgpuInstanceGetMdevUUID 44
#define RPC_nvmlDeviceGetMinorNumber 45
#define RPC_nvmlDeviceGetBoardPartNumber 46
#define RPC_nvmlDeviceGetInforomVersion 47
#define RPC_nvmlDeviceGetInforomImageVersion 48
#define RPC_nvmlDeviceGetInforomConfigurationChecksum 49
#define RPC_nvmlDeviceValidateInforom 50
#define RPC_nvmlDeviceGetDisplayMode 51
#define RPC_nvmlDeviceGetDisplayActive 52
#define RPC_nvmlDeviceGetPersistenceMode 53
#define RPC_nvmlDeviceGetPciInfo_v3 54
#define RPC_nvmlDeviceGetMaxPcieLinkGeneration 55
#define RPC_nvmlDeviceGetGpuMaxPcieLinkGeneration 56
#define RPC_nvmlDeviceGetMaxPcieLinkWidth 57
#define RPC_nvmlDeviceGetCurrPcieLinkGeneration 58
#define RPC_nvmlDeviceGetCurrPcieLinkWidth 59
#define RPC_nvmlDeviceGetPcieThroughput 60
#define RPC_nvmlDeviceGetPcieReplayCounter 61
#define RPC_nvmlDeviceGetClockInfo 62
#define RPC_nvmlDeviceGetMaxClockInfo 63
#define RPC_nvmlDeviceGetApplicationsClock 64
#define RPC_nvmlDeviceGetDefaultApplicationsClock 65
#define RPC_nvmlDeviceResetApplicationsClocks 66
#define RPC_nvmlDeviceGetClock 67
#define RPC_nvmlDeviceGetMaxCustomerBoostClock 68
#define RPC_nvmlDeviceGetSupportedMemoryClocks 69
#define RPC_nvmlDeviceGetSupportedGraphicsClocks 70
#define RPC_nvmlDeviceGetAutoBoostedClocksEnabled 71
#define RPC_nvmlDeviceSetAutoBoostedClocksEnabled 72
#define RPC_nvmlDeviceSetDefaultAutoBoostedClocksEnabled 73
#define RPC_nvmlDeviceGetFanSpeed 74
#define RPC_nvmlDeviceGetFanSpeed_v2 75
#define RPC_nvmlDeviceGetTargetFanSpeed 76
#define RPC_nvmlDeviceSetDefaultFanSpeed_v2 77
#define RPC_nvmlDeviceGetMinMaxFanSpeed 78
#define RPC_nvmlDeviceGetFanControlPolicy_v2 79
#define RPC_nvmlDeviceSetFanControlPolicy 80
#define RPC_nvmlDeviceGetNumFans 81
#define RPC_nvmlDeviceGetTemperature 82
#define RPC_nvmlDeviceGetTemperatureThreshold 83
#define RPC_nvmlDeviceSetTemperatureThreshold 84
#define RPC_nvmlDeviceGetThermalSettings 85
#define RPC_nvmlDeviceGetPerformanceState 86
#define RPC_nvmlDeviceGetCurrentClocksThrottleReasons 87
#define RPC_nvmlDeviceGetSupportedClocksThrottleReasons 88
#define RPC_nvmlDeviceGetPowerState 89
#define RPC_nvmlDeviceGetPowerManagementMode 90
#define RPC_nvmlDeviceGetPowerManagementLimit 91
#define RPC_nvmlDeviceGetPowerManagementLimitConstraints 92
#define RPC_nvmlDeviceGetPowerManagementDefaultLimit 93
#define RPC_nvmlDeviceGetPowerUsage 94
#define RPC_nvmlDeviceGetTotalEnergyConsumption 95
#define RPC_nvmlDeviceGetEnforcedPowerLimit 96
#define RPC_nvmlDeviceGetGpuOperationMode 97
#define RPC_nvmlDeviceGetMemoryInfo 98
#define RPC_nvmlDeviceGetMemoryInfo_v2 99
#define RPC_nvmlDeviceGetComputeMode 100
#define RPC_nvmlDeviceGetCudaComputeCapability 101
#define RPC_nvmlDeviceGetEccMode 102
#define RPC_nvmlDeviceGetDefaultEccMode 103
#define RPC_nvmlDeviceGetBoardId 104
#define RPC_nvmlDeviceGetMultiGpuBoard 105
#define RPC_nvmlDeviceGetTotalEccErrors 106
#define RPC_nvmlDeviceGetDetailedEccErrors 107
#define RPC_nvmlDeviceGetMemoryErrorCounter 108
#define RPC_nvmlDeviceGetUtilizationRates 109
#define RPC_nvmlDeviceGetEncoderUtilization 110
#define RPC_nvmlDeviceGetEncoderCapacity 111
#define RPC_nvmlDeviceGetEncoderStats 112
#define RPC_nvmlDeviceGetEncoderSessions 113
#define RPC_nvmlDeviceGetDecoderUtilization 114
#define RPC_nvmlDeviceGetFBCStats 115
#define RPC_nvmlDeviceGetFBCSessions 116
#define RPC_nvmlDeviceGetVbiosVersion 117
#define RPC_nvmlDeviceGetBridgeChipInfo 118
#define RPC_nvmlDeviceGetComputeRunningProcesses_v3 119
#define RPC_nvmlDeviceGetGraphicsRunningProcesses_v3 120
#define RPC_nvmlDeviceGetMPSComputeRunningProcesses_v3 121
#define RPC_nvmlDeviceOnSameBoard 122
#define RPC_nvmlDeviceGetAPIRestriction 123
#define RPC_nvmlDeviceGetSamples 124
#define RPC_nvmlDeviceGetBAR1MemoryInfo 125
#define RPC_nvmlDeviceGetViolationStatus 126
#define RPC_nvmlDeviceGetIrqNum 127
#define RPC_nvmlDeviceGetNumGpuCores 128
#define RPC_nvmlDeviceGetPowerSource 129
#define RPC_nvmlDeviceGetMemoryBusWidth 130
#define RPC_nvmlDeviceGetPcieLinkMaxSpeed 131
#define RPC_nvmlDeviceGetPcieSpeed 132
#define RPC_nvmlDeviceGetAdaptiveClockInfoStatus 133
#define RPC_nvmlDeviceGetAccountingMode 134
#define RPC_nvmlDeviceGetAccountingStats 135
#define RPC_nvmlDeviceGetAccountingPids 136
#define RPC_nvmlDeviceGetAccountingBufferSize 137
#define RPC_nvmlDeviceGetRetiredPages 138
#define RPC_nvmlDeviceGetRetiredPages_v2 139
#define RPC_nvmlDeviceGetRetiredPagesPendingStatus 140
#define RPC_nvmlDeviceGetRemappedRows 141
#define RPC_nvmlDeviceGetRowRemapperHistogram 142
#define RPC_nvmlDeviceGetArchitecture 143
#define RPC_nvmlUnitSetLedState 144
#define RPC_nvmlDeviceSetPersistenceMode 145
#define RPC_nvmlDeviceSetComputeMode 146
#define RPC_nvmlDeviceSetEccMode 147
#define RPC_nvmlDeviceClearEccErrorCounts 148
#define RPC_nvmlDeviceSetDriverModel 149
#define RPC_nvmlDeviceSetGpuLockedClocks 150
#define RPC_nvmlDeviceResetGpuLockedClocks 151
#define RPC_nvmlDeviceSetMemoryLockedClocks 152
#define RPC_nvmlDeviceResetMemoryLockedClocks 153
#define RPC_nvmlDeviceSetApplicationsClocks 154
#define RPC_nvmlDeviceGetClkMonStatus 155
#define RPC_nvmlDeviceSetPowerManagementLimit 156
#define RPC_nvmlDeviceSetGpuOperationMode 157
#define RPC_nvmlDeviceSetAPIRestriction 158
#define RPC_nvmlDeviceSetAccountingMode 159
#define RPC_nvmlDeviceClearAccountingPids 160
#define RPC_nvmlDeviceGetNvLinkState 161
#define RPC_nvmlDeviceGetNvLinkVersion 162
#define RPC_nvmlDeviceGetNvLinkCapability 163
#define RPC_nvmlDeviceGetNvLinkRemotePciInfo_v2 164
#define RPC_nvmlDeviceGetNvLinkErrorCounter 165
#define RPC_nvmlDeviceResetNvLinkErrorCounters 166
#define RPC_nvmlDeviceSetNvLinkUtilizationControl 167
#define RPC_nvmlDeviceGetNvLinkUtilizationControl 168
#define RPC_nvmlDeviceGetNvLinkUtilizationCounter 169
#define RPC_nvmlDeviceFreezeNvLinkUtilizationCounter 170
#define RPC_nvmlDeviceResetNvLinkUtilizationCounter 171
#define RPC_nvmlDeviceGetNvLinkRemoteDeviceType 172
#define RPC_nvmlEventSetCreate 173
#define RPC_nvmlDeviceRegisterEvents 174
#define RPC_nvmlDeviceGetSupportedEventTypes 175
#define RPC_nvmlEventSetWait_v2 176
#define RPC_nvmlEventSetFree 177
#define RPC_nvmlDeviceModifyDrainState 178
#define RPC_nvmlDeviceQueryDrainState 179
#define RPC_nvmlDeviceRemoveGpu_v2 180
#define RPC_nvmlDeviceDiscoverGpus 181
#define RPC_nvmlDeviceGetFieldValues 182
#define RPC_nvmlDeviceClearFieldValues 183
#define RPC_nvmlDeviceGetVirtualizationMode 184
#define RPC_nvmlDeviceGetHostVgpuMode 185
#define RPC_nvmlDeviceSetVirtualizationMode 186
#define RPC_nvmlDeviceGetGridLicensableFeatures_v4 187
#define RPC_nvmlDeviceGetProcessUtilization 188
#define RPC_nvmlDeviceGetGspFirmwareVersion 189
#define RPC_nvmlDeviceGetGspFirmwareMode 190
#define RPC_nvmlGetVgpuDriverCapabilities 191
#define RPC_nvmlDeviceGetVgpuCapabilities 192
#define RPC_nvmlDeviceGetSupportedVgpus 193
#define RPC_nvmlDeviceGetCreatableVgpus 194
#define RPC_nvmlVgpuTypeGetClass 195
#define RPC_nvmlVgpuTypeGetName 196
#define RPC_nvmlVgpuTypeGetGpuInstanceProfileId 197
#define RPC_nvmlVgpuTypeGetDeviceID 198
#define RPC_nvmlVgpuTypeGetFramebufferSize 199
#define RPC_nvmlVgpuTypeGetNumDisplayHeads 200
#define RPC_nvmlVgpuTypeGetResolution 201
#define RPC_nvmlVgpuTypeGetLicense 202
#define RPC_nvmlVgpuTypeGetFrameRateLimit 203
#define RPC_nvmlVgpuTypeGetMaxInstances 204
#define RPC_nvmlVgpuTypeGetMaxInstancesPerVm 205
#define RPC_nvmlDeviceGetActiveVgpus 206
#define RPC_nvmlVgpuInstanceGetVmID 207
#define RPC_nvmlVgpuInstanceGetUUID 208
#define RPC_nvmlVgpuInstanceGetVmDriverVersion 209
#define RPC_nvmlVgpuInstanceGetFbUsage 210
#define RPC_nvmlVgpuInstanceGetLicenseStatus 211
#define RPC_nvmlVgpuInstanceGetType 212
#define RPC_nvmlVgpuInstanceGetFrameRateLimit 213
#define RPC_nvmlVgpuInstanceGetEccMode 214
#define RPC_nvmlVgpuInstanceGetEncoderCapacity 215
#define RPC_nvmlVgpuInstanceSetEncoderCapacity 216
#define RPC_nvmlVgpuInstanceGetEncoderStats 217
#define RPC_nvmlVgpuInstanceGetEncoderSessions 218
#define RPC_nvmlVgpuInstanceGetFBCStats 219
#define RPC_nvmlVgpuInstanceGetFBCSessions 220
#define RPC_nvmlVgpuInstanceGetGpuInstanceId 221
#define RPC_nvmlVgpuInstanceGetGpuPciId 222
#define RPC_nvmlVgpuTypeGetCapabilities 223
#define RPC_nvmlVgpuInstanceGetMetadata 224
#define RPC_nvmlDeviceGetVgpuMetadata 225
#define RPC_nvmlGetVgpuCompatibility 226
#define RPC_nvmlDeviceGetPgpuMetadataString 227
#define RPC_nvmlDeviceGetVgpuSchedulerLog 228
#define RPC_nvmlDeviceGetVgpuSchedulerState 229
#define RPC_nvmlDeviceGetVgpuSchedulerCapabilities 230
#define RPC_nvmlGetVgpuVersion 231
#define RPC_nvmlSetVgpuVersion 232
#define RPC_nvmlDeviceGetVgpuUtilization 233
#define RPC_nvmlDeviceGetVgpuProcessUtilization 234
#define RPC_nvmlVgpuInstanceGetAccountingMode 235
#define RPC_nvmlVgpuInstanceGetAccountingPids 236
#define RPC_nvmlVgpuInstanceGetAccountingStats 237
#define RPC_nvmlVgpuInstanceClearAccountingPids 238
#define RPC_nvmlVgpuInstanceGetLicenseInfo_v2 239
#define RPC_nvmlGetExcludedDeviceCount 240
#define RPC_nvmlGetExcludedDeviceInfoByIndex 241
#define RPC_nvmlDeviceSetMigMode 242
#define RPC_nvmlDeviceGetMigMode 243
#define RPC_nvmlDeviceGetGpuInstanceProfileInfo 244
#define RPC_nvmlDeviceGetGpuInstanceProfileInfoV 245
#define RPC_nvmlDeviceGetGpuInstancePossiblePlacements_v2 246
#define RPC_nvmlDeviceGetGpuInstanceRemainingCapacity 247
#define RPC_nvmlDeviceCreateGpuInstance 248
#define RPC_nvmlDeviceCreateGpuInstanceWithPlacement 249
#define RPC_nvmlGpuInstanceDestroy 250
#define RPC_nvmlDeviceGetGpuInstances 251
#define RPC_nvmlDeviceGetGpuInstanceById 252
#define RPC_nvmlGpuInstanceGetInfo 253
#define RPC_nvmlGpuInstanceGetComputeInstanceProfileInfo 254
#define RPC_nvmlGpuInstanceGetComputeInstanceProfileInfoV 255
#define RPC_nvmlGpuInstanceGetComputeInstanceRemainingCapacity 256
#define RPC_nvmlGpuInstanceGetComputeInstancePossiblePlacements 257
#define RPC_nvmlGpuInstanceCreateComputeInstance 258
#define RPC_nvmlGpuInstanceCreateComputeInstanceWithPlacement 259
#define RPC_nvmlComputeInstanceDestroy 260
#define RPC_nvmlGpuInstanceGetComputeInstances 261
#define RPC_nvmlGpuInstanceGetComputeInstanceById 262
#define RPC_nvmlComputeInstanceGetInfo_v2 263
#define RPC_nvmlDeviceIsMigDeviceHandle 264
#define RPC_nvmlDeviceGetGpuInstanceId 265
#define RPC_nvmlDeviceGetComputeInstanceId 266
#define RPC_nvmlDeviceGetMaxMigDeviceCount 267
#define RPC_nvmlDeviceGetMigDeviceHandleByIndex 268
#define RPC_nvmlDeviceGetDeviceHandleFromMigDeviceHandle 269
#define RPC_nvmlDeviceGetBusType 270
#define RPC_nvmlDeviceGetDynamicPstatesInfo 271
#define RPC_nvmlDeviceSetFanSpeed_v2 272
#define RPC_nvmlDeviceGetGpcClkVfOffset 273
#define RPC_nvmlDeviceSetGpcClkVfOffset 274
#define RPC_nvmlDeviceGetMemClkVfOffset 275
#define RPC_nvmlDeviceSetMemClkVfOffset 276
#define RPC_nvmlDeviceGetMinMaxClockOfPState 277
#define RPC_nvmlDeviceGetSupportedPerformanceStates 278
#define RPC_nvmlDeviceGetGpcClkMinMaxVfOffset 279
#define RPC_nvmlDeviceGetMemClkMinMaxVfOffset 280
#define RPC_nvmlDeviceGetGpuFabricInfo 281
#define RPC_nvmlGpmMetricsGet 282
#define RPC_nvmlGpmSampleFree 283
#define RPC_nvmlGpmSampleAlloc 284
#define RPC_nvmlGpmSampleGet 285
#define RPC_nvmlGpmMigSampleGet 286
#define RPC_nvmlGpmQueryDeviceSupport 287
#define RPC_nvmlDeviceCcuGetStreamState 288
#define RPC_nvmlDeviceCcuSetStreamState 289
#define RPC_nvmlDeviceSetNvLinkDeviceLowPowerThreshold 290
#define RPC_cudaDeviceReset 291
#define RPC_cudaDeviceSynchronize 292
#define RPC_cudaDeviceSetLimit 293
#define RPC_cudaDeviceGetLimit 294
#define RPC_cudaDeviceGetTexture1DLinearMaxWidth 295
#define RPC_cudaDeviceGetCacheConfig 296
#define RPC_cudaDeviceGetStreamPriorityRange 297
#define RPC_cudaDeviceSetCacheConfig 298
#define RPC_cudaDeviceGetByPCIBusId 299
#define RPC_cudaDeviceGetPCIBusId 300
#define RPC_cudaIpcGetEventHandle 301
#define RPC_cudaIpcOpenEventHandle 302
#define RPC_cudaIpcOpenMemHandle 303
#define RPC_cudaDeviceFlushGPUDirectRDMAWrites 304
#define RPC_cudaDeviceGetSharedMemConfig 305
#define RPC_cudaDeviceSetSharedMemConfig 306
#define RPC_cudaThreadExit 307
#define RPC_cudaThreadSynchronize 308
#define RPC_cudaThreadSetLimit 309
#define RPC_cudaThreadGetLimit 310
#define RPC_cudaThreadGetCacheConfig 311
#define RPC_cudaThreadSetCacheConfig 312
#define RPC_cudaGetLastError 313
#define RPC_cudaPeekAtLastError 314
#define RPC_cudaGetErrorName 315
#define RPC_cudaGetErrorString 316
#define RPC_cudaGetDeviceCount 317
#define RPC_cudaGetDeviceProperties_v2 318
#define RPC_cudaDeviceGetAttribute 319
#define RPC_cudaDeviceGetDefaultMemPool 320
#define RPC_cudaDeviceSetMemPool 321
#define RPC_cudaDeviceGetMemPool 322
#define RPC_cudaDeviceGetP2PAttribute 323
#define RPC_cudaChooseDevice 324
#define RPC_cudaInitDevice 325
#define RPC_cudaSetDevice 326
#define RPC_cudaGetDevice 327
#define RPC_cudaSetValidDevices 328
#define RPC_cudaSetDeviceFlags 329
#define RPC_cudaGetDeviceFlags 330
#define RPC_cudaStreamCreate 331
#define RPC_cudaStreamCreateWithFlags 332
#define RPC_cudaStreamCreateWithPriority 333
#define RPC_cudaStreamGetPriority 334
#define RPC_cudaStreamGetFlags 335
#define RPC_cudaStreamGetId 336
#define RPC_cudaCtxResetPersistingL2Cache 337
#define RPC_cudaStreamCopyAttributes 338
#define RPC_cudaStreamGetAttribute 339
#define RPC_cudaStreamSetAttribute 340
#define RPC_cudaStreamDestroy 341
#define RPC_cudaStreamWaitEvent 342
#define RPC_cudaStreamSynchronize 343
#define RPC_cudaStreamQuery 344
#define RPC_cudaStreamBeginCapture 345
#define RPC_cudaThreadExchangeStreamCaptureMode 346
#define RPC_cudaStreamEndCapture 347
#define RPC_cudaStreamIsCapturing 348
#define RPC_cudaStreamGetCaptureInfo_v2 349
#define RPC_cudaStreamUpdateCaptureDependencies 350
#define RPC_cudaEventCreate 351
#define RPC_cudaEventCreateWithFlags 352
#define RPC_cudaEventRecord 353
#define RPC_cudaEventRecordWithFlags 354
#define RPC_cudaEventQuery 355
#define RPC_cudaEventSynchronize 356
#define RPC_cudaEventDestroy 357
#define RPC_cudaEventElapsedTime 358
#define RPC_cudaImportExternalMemory 359
#define RPC_cudaExternalMemoryGetMappedBuffer 360
#define RPC_cudaExternalMemoryGetMappedMipmappedArray 361
#define RPC_cudaDestroyExternalMemory 362
#define RPC_cudaImportExternalSemaphore 363
#define RPC_cudaSignalExternalSemaphoresAsync_v2 364
#define RPC_cudaWaitExternalSemaphoresAsync_v2 365
#define RPC_cudaDestroyExternalSemaphore 366
#define RPC_cudaLaunchKernel 367
#define RPC_cudaLaunchKernelExC 368
#define RPC_cudaLaunchCooperativeKernel 369
#define RPC_cudaLaunchCooperativeKernelMultiDevice 370
#define RPC_cudaFuncSetCacheConfig 371
#define RPC_cudaFuncGetAttributes 372
#define RPC_cudaFuncSetAttribute 373
#define RPC_cudaSetDoubleForDevice 374
#define RPC_cudaSetDoubleForHost 375
#define RPC_cudaFuncSetSharedMemConfig 376
#define RPC_cudaOccupancyMaxActiveBlocksPerMultiprocessor 377
#define RPC_cudaOccupancyAvailableDynamicSMemPerBlock 378
#define RPC_cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags 379
#define RPC_cudaOccupancyMaxPotentialClusterSize 380
#define RPC_cudaOccupancyMaxActiveClusters 381
#define RPC_cudaMallocManaged 382
#define RPC_cudaMalloc 383
#define RPC_cudaMallocHost 384
#define RPC_cudaMallocPitch 385
#define RPC_cudaMallocArray 386
#define RPC_cudaFree 387
#define RPC_cudaFreeHost 388
#define RPC_cudaFreeArray 389
#define RPC_cudaFreeMipmappedArray 390
#define RPC_cudaHostAlloc 391
#define RPC_cudaMalloc3D 392
#define RPC_cudaMalloc3DArray 393
#define RPC_cudaMallocMipmappedArray 394
#define RPC_cudaGetMipmappedArrayLevel 395
#define RPC_cudaMemcpy3D 396
#define RPC_cudaMemcpy3DPeer 397
#define RPC_cudaMemcpy3DAsync 398
#define RPC_cudaMemcpy3DPeerAsync 399
#define RPC_cudaMemGetInfo 400
#define RPC_cudaArrayGetInfo 401
#define RPC_cudaArrayGetPlane 402
#define RPC_cudaArrayGetMemoryRequirements 403
#define RPC_cudaMipmappedArrayGetMemoryRequirements 404
#define RPC_cudaArrayGetSparseProperties 405
#define RPC_cudaMipmappedArrayGetSparseProperties 406
#define RPC_cudaMemcpy 407
#define RPC_cudaMemcpy2DToArray 408
#define RPC_cudaMemcpy2DArrayToArray 409
#define RPC_cudaMemcpyToSymbol 410
#define RPC_cudaMemcpyAsync 411
#define RPC_cudaMemcpy2DToArrayAsync 412
#define RPC_cudaMemcpyToSymbolAsync 413
#define RPC_cudaMemset 414
#define RPC_cudaMemset2D 415
#define RPC_cudaMemset3D 416
#define RPC_cudaMemsetAsync 417
#define RPC_cudaMemset2DAsync 418
#define RPC_cudaMemset3DAsync 419
#define RPC_cudaGetSymbolAddress 420
#define RPC_cudaGetSymbolSize 421
#define RPC_cudaMemPrefetchAsync 422
#define RPC_cudaMemAdvise 423
#define RPC_cudaMemRangeGetAttributes 424
#define RPC_cudaMemcpyToArray 425
#define RPC_cudaMemcpyArrayToArray 426
#define RPC_cudaMemcpyToArrayAsync 427
#define RPC_cudaMallocAsync 428
#define RPC_cudaMemPoolTrimTo 429
#define RPC_cudaMemPoolSetAccess 430
#define RPC_cudaMemPoolGetAccess 431
#define RPC_cudaMemPoolCreate 432
#define RPC_cudaMemPoolDestroy 433
#define RPC_cudaMallocFromPoolAsync 434
#define RPC_cudaMemPoolImportPointer 435
#define RPC_cudaPointerGetAttributes 436
#define RPC_cudaDeviceCanAccessPeer 437
#define RPC_cudaDeviceEnablePeerAccess 438
#define RPC_cudaDeviceDisablePeerAccess 439
#define RPC_cudaGraphicsUnregisterResource 440
#define RPC_cudaGraphicsResourceSetMapFlags 441
#define RPC_cudaGraphicsMapResources 442
#define RPC_cudaGraphicsUnmapResources 443
#define RPC_cudaGraphicsResourceGetMappedPointer 444
#define RPC_cudaGraphicsSubResourceGetMappedArray 445
#define RPC_cudaGraphicsResourceGetMappedMipmappedArray 446
#define RPC_cudaGetChannelDesc 447
#define RPC_cudaCreateChannelDesc 448
#define RPC_cudaCreateTextureObject 449
#define RPC_cudaDestroyTextureObject 450
#define RPC_cudaGetTextureObjectResourceDesc 451
#define RPC_cudaGetTextureObjectTextureDesc 452
#define RPC_cudaGetTextureObjectResourceViewDesc 453
#define RPC_cudaCreateSurfaceObject 454
#define RPC_cudaDestroySurfaceObject 455
#define RPC_cudaGetSurfaceObjectResourceDesc 456
#define RPC_cudaDriverGetVersion 457
#define RPC_cudaRuntimeGetVersion 458
#define RPC_cudaGraphCreate 459
#define RPC_cudaGraphAddKernelNode 460
#define RPC_cudaGraphKernelNodeGetParams 461
#define RPC_cudaGraphKernelNodeSetParams 462
#define RPC_cudaGraphKernelNodeCopyAttributes 463
#define RPC_cudaGraphKernelNodeGetAttribute 464
#define RPC_cudaGraphKernelNodeSetAttribute 465
#define RPC_cudaGraphAddMemcpyNode 466
#define RPC_cudaGraphAddMemcpyNodeToSymbol 467
#define RPC_cudaGraphMemcpyNodeGetParams 468
#define RPC_cudaGraphMemcpyNodeSetParams 469
#define RPC_cudaGraphMemcpyNodeSetParamsToSymbol 470
#define RPC_cudaGraphAddMemsetNode 471
#define RPC_cudaGraphMemsetNodeGetParams 472
#define RPC_cudaGraphMemsetNodeSetParams 473
#define RPC_cudaGraphAddHostNode 474
#define RPC_cudaGraphHostNodeGetParams 475
#define RPC_cudaGraphHostNodeSetParams 476
#define RPC_cudaGraphAddChildGraphNode 477
#define RPC_cudaGraphChildGraphNodeGetGraph 478
#define RPC_cudaGraphAddEmptyNode 479
#define RPC_cudaGraphAddEventRecordNode 480
#define RPC_cudaGraphEventRecordNodeGetEvent 481
#define RPC_cudaGraphEventRecordNodeSetEvent 482
#define RPC_cudaGraphAddEventWaitNode 483
#define RPC_cudaGraphEventWaitNodeGetEvent 484
#define RPC_cudaGraphEventWaitNodeSetEvent 485
#define RPC_cudaGraphAddExternalSemaphoresSignalNode 486
#define RPC_cudaGraphExternalSemaphoresSignalNodeGetParams 487
#define RPC_cudaGraphExternalSemaphoresSignalNodeSetParams 488
#define RPC_cudaGraphAddExternalSemaphoresWaitNode 489
#define RPC_cudaGraphExternalSemaphoresWaitNodeGetParams 490
#define RPC_cudaGraphExternalSemaphoresWaitNodeSetParams 491
#define RPC_cudaGraphAddMemAllocNode 492
#define RPC_cudaGraphMemAllocNodeGetParams 493
#define RPC_cudaGraphAddMemFreeNode 494
#define RPC_cudaDeviceGraphMemTrim 495
#define RPC_cudaDeviceGetGraphMemAttribute 496
#define RPC_cudaGraphClone 497
#define RPC_cudaGraphNodeFindInClone 498
#define RPC_cudaGraphNodeGetType 499
#define RPC_cudaGraphGetNodes 500
#define RPC_cudaGraphGetRootNodes 501
#define RPC_cudaGraphGetEdges 502
#define RPC_cudaGraphNodeGetDependencies 503
#define RPC_cudaGraphNodeGetDependentNodes 504
#define RPC_cudaGraphAddDependencies 505
#define RPC_cudaGraphRemoveDependencies 506
#define RPC_cudaGraphDestroyNode 507
#define RPC_cudaGraphInstantiate 508
#define RPC_cudaGraphInstantiateWithFlags 509
#define RPC_cudaGraphInstantiateWithParams 510
#define RPC_cudaGraphExecGetFlags 511
#define RPC_cudaGraphExecKernelNodeSetParams 512
#define RPC_cudaGraphExecMemcpyNodeSetParams 513
#define RPC_cudaGraphExecMemcpyNodeSetParamsToSymbol 514
#define RPC_cudaGraphExecMemsetNodeSetParams 515
#define RPC_cudaGraphExecHostNodeSetParams 516
#define RPC_cudaGraphExecChildGraphNodeSetParams 517
#define RPC_cudaGraphExecEventRecordNodeSetEvent 518
#define RPC_cudaGraphExecEventWaitNodeSetEvent 519
#define RPC_cudaGraphExecExternalSemaphoresSignalNodeSetParams 520
#define RPC_cudaGraphExecExternalSemaphoresWaitNodeSetParams 521
#define RPC_cudaGraphNodeSetEnabled 522
#define RPC_cudaGraphNodeGetEnabled 523
#define RPC_cudaGraphExecUpdate 524
#define RPC_cudaGraphUpload 525
#define RPC_cudaGraphLaunch 526
#define RPC_cudaGraphExecDestroy 527
#define RPC_cudaGraphDestroy 528
#define RPC_cudaGraphDebugDotPrint 529
#define RPC_cudaUserObjectRetain 530
#define RPC_cudaUserObjectRelease 531
#define RPC_cudaGraphRetainUserObject 532
#define RPC_cudaGraphReleaseUserObject 533
#define RPC_cudaGetDriverEntryPoint 534
#define RPC_cudaGetExportTable 535
#define RPC_cudaGetFuncBySymbol 536
#define RPC_cublasCreate_v2 537
#define RPC_cublasDestroy_v2 538
#define RPC_cublasGetVersion_v2 539
#define RPC_cublasGetProperty 540
#define RPC_cublasGetCudartVersion 541
#define RPC_cublasSetStream_v2 542
#define RPC_cublasGetStream_v2 543
#define RPC_cublasGetPointerMode_v2 544
#define RPC_cublasSetPointerMode_v2 545
#define RPC_cublasGetAtomicsMode 546
#define RPC_cublasSetAtomicsMode 547
#define RPC_cublasGetMathMode 548
#define RPC_cublasSetMathMode 549
#define RPC_cublasGetSmCountTarget 550
#define RPC_cublasSetSmCountTarget 551
#define RPC_cublasGetStatusName 552
#define RPC_cublasGetStatusString 553
#define RPC_cublasLoggerConfigure 554
#define RPC_cublasSetLoggerCallback 555
#define RPC_cublasGetLoggerCallback 556
#define RPC_cublasXerbla 557
#define RPC_cublasSnrm2_v2 558
#define RPC_cublasSnrm2_v2_64 559
#define RPC_cublasDnrm2_v2 560
#define RPC_cublasDnrm2_v2_64 561
#define RPC_cublasScnrm2_v2 562
#define RPC_cublasScnrm2_v2_64 563
#define RPC_cublasDznrm2_v2 564
#define RPC_cublasDznrm2_v2_64 565
#define RPC_cublasSdot_v2 566
#define RPC_cublasSdot_v2_64 567
#define RPC_cublasDdot_v2 568
#define RPC_cublasDdot_v2_64 569
#define RPC_cublasCdotu_v2 570
#define RPC_cublasCdotu_v2_64 571
#define RPC_cublasCdotc_v2 572
#define RPC_cublasCdotc_v2_64 573
#define RPC_cublasZdotu_v2 574
#define RPC_cublasZdotu_v2_64 575
#define RPC_cublasZdotc_v2 576
#define RPC_cublasZdotc_v2_64 577
#define RPC_cublasSscal_v2 578
#define RPC_cublasSscal_v2_64 579
#define RPC_cublasDscal_v2 580
#define RPC_cublasDscal_v2_64 581
#define RPC_cublasCscal_v2 582
#define RPC_cublasCscal_v2_64 583
#define RPC_cublasCsscal_v2 584
#define RPC_cublasCsscal_v2_64 585
#define RPC_cublasZscal_v2 586
#define RPC_cublasZscal_v2_64 587
#define RPC_cublasZdscal_v2 588
#define RPC_cublasZdscal_v2_64 589
#define RPC_cublasSaxpy_v2 590
#define RPC_cublasSaxpy_v2_64 591
#define RPC_cublasDaxpy_v2 592
#define RPC_cublasDaxpy_v2_64 593
#define RPC_cublasCaxpy_v2 594
#define RPC_cublasCaxpy_v2_64 595
#define RPC_cublasZaxpy_v2 596
#define RPC_cublasZaxpy_v2_64 597
#define RPC_cublasScopy_v2 598
#define RPC_cublasScopy_v2_64 599
#define RPC_cublasDcopy_v2 600
#define RPC_cublasDcopy_v2_64 601
#define RPC_cublasCcopy_v2 602
#define RPC_cublasCcopy_v2_64 603
#define RPC_cublasZcopy_v2 604
#define RPC_cublasZcopy_v2_64 605
#define RPC_cublasSswap_v2 606
#define RPC_cublasSswap_v2_64 607
#define RPC_cublasDswap_v2 608
#define RPC_cublasDswap_v2_64 609
#define RPC_cublasCswap_v2 610
#define RPC_cublasCswap_v2_64 611
#define RPC_cublasZswap_v2 612
#define RPC_cublasZswap_v2_64 613
#define RPC_cublasIsamax_v2 614
#define RPC_cublasIsamax_v2_64 615
#define RPC_cublasIdamax_v2 616
#define RPC_cublasIdamax_v2_64 617
#define RPC_cublasIcamax_v2 618
#define RPC_cublasIcamax_v2_64 619
#define RPC_cublasIzamax_v2 620
#define RPC_cublasIzamax_v2_64 621
#define RPC_cublasIamaxEx 622
#define RPC_cublasIamaxEx_64 623
#define RPC_cublasIsamin_v2 624
#define RPC_cublasIsamin_v2_64 625
#define RPC_cublasIdamin_v2 626
#define RPC_cublasIdamin_v2_64 627
#define RPC_cublasIcamin_v2 628
#define RPC_cublasIcamin_v2_64 629
#define RPC_cublasIzamin_v2 630
#define RPC_cublasIzamin_v2_64 631
#define RPC_cublasIaminEx 632
#define RPC_cublasIaminEx_64 633
#define RPC_cublasSasum_v2 634
#define RPC_cublasSasum_v2_64 635
#define RPC_cublasDasum_v2 636
#define RPC_cublasDasum_v2_64 637
#define RPC_cublasScasum_v2 638
#define RPC_cublasScasum_v2_64 639
#define RPC_cublasDzasum_v2 640
#define RPC_cublasDzasum_v2_64 641
#define RPC_cublasSrot_v2 642
#define RPC_cublasSrot_v2_64 643
#define RPC_cublasDrot_v2 644
#define RPC_cublasDrot_v2_64 645
#define RPC_cublasCrot_v2 646
#define RPC_cublasCrot_v2_64 647
#define RPC_cublasCsrot_v2 648
#define RPC_cublasCsrot_v2_64 649
#define RPC_cublasZrot_v2 650
#define RPC_cublasZrot_v2_64 651
#define RPC_cublasZdrot_v2 652
#define RPC_cublasZdrot_v2_64 653
#define RPC_cublasSrotg_v2 654
#define RPC_cublasDrotg_v2 655
#define RPC_cublasCrotg_v2 656
#define RPC_cublasZrotg_v2 657
#define RPC_cublasSrotm_v2 658
#define RPC_cublasSrotm_v2_64 659
#define RPC_cublasDrotm_v2 660
#define RPC_cublasDrotm_v2_64 661
#define RPC_cublasSrotmg_v2 662
#define RPC_cublasDrotmg_v2 663
#define RPC_cublasSgemv_v2 664
#define RPC_cublasSgemv_v2_64 665
#define RPC_cublasDgemv_v2 666
#define RPC_cublasDgemv_v2_64 667
#define RPC_cublasCgemv_v2 668
#define RPC_cublasCgemv_v2_64 669
#define RPC_cublasZgemv_v2 670
#define RPC_cublasZgemv_v2_64 671
#define RPC_cublasSgbmv_v2 672
#define RPC_cublasSgbmv_v2_64 673
#define RPC_cublasDgbmv_v2 674
#define RPC_cublasDgbmv_v2_64 675
#define RPC_cublasCgbmv_v2 676
#define RPC_cublasCgbmv_v2_64 677
#define RPC_cublasZgbmv_v2 678
#define RPC_cublasZgbmv_v2_64 679
#define RPC_cublasStrmv_v2 680
#define RPC_cublasStrmv_v2_64 681
#define RPC_cublasDtrmv_v2 682
#define RPC_cublasDtrmv_v2_64 683
#define RPC_cublasCtrmv_v2 684
#define RPC_cublasCtrmv_v2_64 685
#define RPC_cublasZtrmv_v2 686
#define RPC_cublasZtrmv_v2_64 687
#define RPC_cublasStbmv_v2 688
#define RPC_cublasStbmv_v2_64 689
#define RPC_cublasDtbmv_v2 690
#define RPC_cublasDtbmv_v2_64 691
#define RPC_cublasCtbmv_v2 692
#define RPC_cublasCtbmv_v2_64 693
#define RPC_cublasZtbmv_v2 694
#define RPC_cublasZtbmv_v2_64 695
#define RPC_cublasStpmv_v2 696
#define RPC_cublasStpmv_v2_64 697
#define RPC_cublasDtpmv_v2 698
#define RPC_cublasDtpmv_v2_64 699
#define RPC_cublasCtpmv_v2 700
#define RPC_cublasCtpmv_v2_64 701
#define RPC_cublasZtpmv_v2 702
#define RPC_cublasZtpmv_v2_64 703
#define RPC_cublasStrsv_v2 704
#define RPC_cublasStrsv_v2_64 705
#define RPC_cublasDtrsv_v2 706
#define RPC_cublasDtrsv_v2_64 707
#define RPC_cublasCtrsv_v2 708
#define RPC_cublasCtrsv_v2_64 709
#define RPC_cublasZtrsv_v2 710
#define RPC_cublasZtrsv_v2_64 711
#define RPC_cublasStpsv_v2 712
#define RPC_cublasStpsv_v2_64 713
#define RPC_cublasDtpsv_v2 714
#define RPC_cublasDtpsv_v2_64 715
#define RPC_cublasCtpsv_v2 716
#define RPC_cublasCtpsv_v2_64 717
#define RPC_cublasZtpsv_v2 718
#define RPC_cublasZtpsv_v2_64 719
#define RPC_cublasStbsv_v2 720
#define RPC_cublasStbsv_v2_64 721
#define RPC_cublasDtbsv_v2 722
#define RPC_cublasDtbsv_v2_64 723
#define RPC_cublasCtbsv_v2 724
#define RPC_cublasCtbsv_v2_64 725
#define RPC_cublasZtbsv_v2 726
#define RPC_cublasZtbsv_v2_64 727
#define RPC_cublasSsymv_v2 728
#define RPC_cublasSsymv_v2_64 729
#define RPC_cublasDsymv_v2 730
#define RPC_cublasDsymv_v2_64 731
#define RPC_cublasCsymv_v2 732
#define RPC_cublasCsymv_v2_64 733
#define RPC_cublasZsymv_v2 734
#define RPC_cublasZsymv_v2_64 735
#define RPC_cublasChemv_v2 736
#define RPC_cublasChemv_v2_64 737
#define RPC_cublasZhemv_v2 738
#define RPC_cublasZhemv_v2_64 739
#define RPC_cublasSsbmv_v2 740
#define RPC_cublasSsbmv_v2_64 741
#define RPC_cublasDsbmv_v2 742
#define RPC_cublasDsbmv_v2_64 743
#define RPC_cublasChbmv_v2 744
#define RPC_cublasChbmv_v2_64 745
#define RPC_cublasZhbmv_v2 746
#define RPC_cublasZhbmv_v2_64 747
#define RPC_cublasSspmv_v2 748
#define RPC_cublasSspmv_v2_64 749
#define RPC_cublasDspmv_v2 750
#define RPC_cublasDspmv_v2_64 751
#define RPC_cublasChpmv_v2 752
#define RPC_cublasChpmv_v2_64 753
#define RPC_cublasZhpmv_v2 754
#define RPC_cublasZhpmv_v2_64 755
#define RPC_cublasSger_v2 756
#define RPC_cublasSger_v2_64 757
#define RPC_cublasDger_v2 758
#define RPC_cublasDger_v2_64 759
#define RPC_cublasCgeru_v2 760
#define RPC_cublasCgeru_v2_64 761
#define RPC_cublasCgerc_v2 762
#define RPC_cublasCgerc_v2_64 763
#define RPC_cublasZgeru_v2 764
#define RPC_cublasZgeru_v2_64 765
#define RPC_cublasZgerc_v2 766
#define RPC_cublasZgerc_v2_64 767
#define RPC_cublasSsyr_v2 768
#define RPC_cublasSsyr_v2_64 769
#define RPC_cublasDsyr_v2 770
#define RPC_cublasDsyr_v2_64 771
#define RPC_cublasCsyr_v2 772
#define RPC_cublasCsyr_v2_64 773
#define RPC_cublasZsyr_v2 774
#define RPC_cublasZsyr_v2_64 775
#define RPC_cublasCher_v2 776
#define RPC_cublasCher_v2_64 777
#define RPC_cublasZher_v2 778
#define RPC_cublasZher_v2_64 779
#define RPC_cublasSspr_v2 780
#define RPC_cublasSspr_v2_64 781
#define RPC_cublasDspr_v2 782
#define RPC_cublasDspr_v2_64 783
#define RPC_cublasChpr_v2 784
#define RPC_cublasChpr_v2_64 785
#define RPC_cublasZhpr_v2 786
#define RPC_cublasZhpr_v2_64 787
#define RPC_cublasSsyr2_v2 788
#define RPC_cublasSsyr2_v2_64 789
#define RPC_cublasDsyr2_v2 790
#define RPC_cublasDsyr2_v2_64 791
#define RPC_cublasCsyr2_v2 792
#define RPC_cublasCsyr2_v2_64 793
#define RPC_cublasZsyr2_v2 794
#define RPC_cublasZsyr2_v2_64 795
#define RPC_cublasCher2_v2 796
#define RPC_cublasCher2_v2_64 797
#define RPC_cublasZher2_v2 798
#define RPC_cublasZher2_v2_64 799
#define RPC_cublasSspr2_v2 800
#define RPC_cublasSspr2_v2_64 801
#define RPC_cublasDspr2_v2 802
#define RPC_cublasDspr2_v2_64 803
#define RPC_cublasChpr2_v2 804
#define RPC_cublasChpr2_v2_64 805
#define RPC_cublasZhpr2_v2 806
#define RPC_cublasZhpr2_v2_64 807
#define RPC_cublasSgemvStridedBatched 808
#define RPC_cublasSgemvStridedBatched_64 809
#define RPC_cublasDgemvStridedBatched 810
#define RPC_cublasDgemvStridedBatched_64 811
#define RPC_cublasCgemvStridedBatched 812
#define RPC_cublasCgemvStridedBatched_64 813
#define RPC_cublasZgemvStridedBatched 814
#define RPC_cublasZgemvStridedBatched_64 815
#define RPC_cublasHSHgemvStridedBatched 816
#define RPC_cublasHSHgemvStridedBatched_64 817
#define RPC_cublasHSSgemvStridedBatched 818
#define RPC_cublasHSSgemvStridedBatched_64 819
#define RPC_cublasTSTgemvStridedBatched 820
#define RPC_cublasTSTgemvStridedBatched_64 821
#define RPC_cublasTSSgemvStridedBatched 822
#define RPC_cublasTSSgemvStridedBatched_64 823
#define RPC_cublasSgemm_v2 824
#define RPC_cublasSgemm_v2_64 825
#define RPC_cublasDgemm_v2 826
#define RPC_cublasDgemm_v2_64 827
#define RPC_cublasCgemm_v2 828
#define RPC_cublasCgemm_v2_64 829
#define RPC_cublasCgemm3m 830
#define RPC_cublasCgemm3m_64 831
#define RPC_cublasZgemm_v2 832
#define RPC_cublasZgemm_v2_64 833
#define RPC_cublasZgemm3m 834
#define RPC_cublasZgemm3m_64 835
#define RPC_cublasHgemm 836
#define RPC_cublasHgemm_64 837
#define RPC_cublasSsyrk_v2 838
#define RPC_cublasSsyrk_v2_64 839
#define RPC_cublasDsyrk_v2 840
#define RPC_cublasDsyrk_v2_64 841
#define RPC_cublasCsyrk_v2 842
#define RPC_cublasCsyrk_v2_64 843
#define RPC_cublasZsyrk_v2 844
#define RPC_cublasZsyrk_v2_64 845
#define RPC_cublasCherk_v2 846
#define RPC_cublasCherk_v2_64 847
#define RPC_cublasZherk_v2 848
#define RPC_cublasZherk_v2_64 849
#define RPC_cublasSsyr2k_v2 850
#define RPC_cublasSsyr2k_v2_64 851
#define RPC_cublasDsyr2k_v2 852
#define RPC_cublasDsyr2k_v2_64 853
#define RPC_cublasCsyr2k_v2 854
#define RPC_cublasCsyr2k_v2_64 855
#define RPC_cublasZsyr2k_v2 856
#define RPC_cublasZsyr2k_v2_64 857
#define RPC_cublasCher2k_v2 858
#define RPC_cublasCher2k_v2_64 859
#define RPC_cublasZher2k_v2 860
#define RPC_cublasZher2k_v2_64 861
#define RPC_cublasSsyrkx 862
#define RPC_cublasSsyrkx_64 863
#define RPC_cublasDsyrkx 864
#define RPC_cublasDsyrkx_64 865
#define RPC_cublasCsyrkx 866
#define RPC_cublasCsyrkx_64 867
#define RPC_cublasZsyrkx 868
#define RPC_cublasZsyrkx_64 869
#define RPC_cublasCherkx 870
#define RPC_cublasCherkx_64 871
#define RPC_cublasZherkx 872
#define RPC_cublasZherkx_64 873
#define RPC_cublasSsymm_v2 874
#define RPC_cublasSsymm_v2_64 875
#define RPC_cublasDsymm_v2 876
#define RPC_cublasDsymm_v2_64 877
#define RPC_cublasCsymm_v2 878
#define RPC_cublasCsymm_v2_64 879
#define RPC_cublasZsymm_v2 880
#define RPC_cublasZsymm_v2_64 881
#define RPC_cublasChemm_v2 882
#define RPC_cublasChemm_v2_64 883
#define RPC_cublasZhemm_v2 884
#define RPC_cublasZhemm_v2_64 885
#define RPC_cublasStrsm_v2 886
#define RPC_cublasStrsm_v2_64 887
#define RPC_cublasDtrsm_v2 888
#define RPC_cublasDtrsm_v2_64 889
#define RPC_cublasCtrsm_v2 890
#define RPC_cublasCtrsm_v2_64 891
#define RPC_cublasZtrsm_v2 892
#define RPC_cublasZtrsm_v2_64 893
#define RPC_cublasStrmm_v2 894
#define RPC_cublasStrmm_v2_64 895
#define RPC_cublasDtrmm_v2 896
#define RPC_cublasDtrmm_v2_64 897
#define RPC_cublasCtrmm_v2 898
#define RPC_cublasCtrmm_v2_64 899
#define RPC_cublasZtrmm_v2 900
#define RPC_cublasZtrmm_v2_64 901
#define RPC_cublasHgemmStridedBatched 902
#define RPC_cublasHgemmStridedBatched_64 903
#define RPC_cublasSgemmStridedBatched 904
#define RPC_cublasSgemmStridedBatched_64 905
#define RPC_cublasDgemmStridedBatched 906
#define RPC_cublasDgemmStridedBatched_64 907
#define RPC_cublasCgemmStridedBatched 908
#define RPC_cublasCgemmStridedBatched_64 909
#define RPC_cublasCgemm3mStridedBatched 910
#define RPC_cublasCgemm3mStridedBatched_64 911
#define RPC_cublasZgemmStridedBatched 912
#define RPC_cublasZgemmStridedBatched_64 913
#define RPC_cublasGemmBatchedEx 914
#define RPC_cublasSgeam 915
#define RPC_cublasSgeam_64 916
#define RPC_cublasDgeam 917
#define RPC_cublasDgeam_64 918
#define RPC_cublasCgeam 919
#define RPC_cublasCgeam_64 920
#define RPC_cublasZgeam 921
#define RPC_cublasZgeam_64 922
#define RPC_cublasSdgmm 923
#define RPC_cublasSdgmm_64 924
#define RPC_cublasDdgmm 925
#define RPC_cublasDdgmm_64 926
#define RPC_cublasCdgmm 927
#define RPC_cublasCdgmm_64 928
#define RPC_cublasZdgmm 929
#define RPC_cublasZdgmm_64 930
#define RPC_cublasStpttr 931
#define RPC_cublasDtpttr 932
#define RPC_cublasCtpttr 933
#define RPC_cublasZtpttr 934
#define RPC_cublasStrttp 935
#define RPC_cublasDtrttp 936
#define RPC_cublasCtrttp 937
#define RPC_cublasZtrttp 938
#define RPC_cublasUint8gemmBias 939
#define RPC_cublasMigrateComputeType 940
#define RPC_cudnnGetMaxDeviceVersion 941
#define RPC_cudnnGetCudartVersion 942
#define RPC_cudnnGetErrorString 943
#define RPC_cudnnGetLastErrorString 944
#define RPC_cudnnQueryRuntimeError 945
#define RPC_cudnnGetProperty 946
#define RPC_cudnnCreate 947
#define RPC_cudnnDestroy 948
#define RPC_cudnnSetStream 949
#define RPC_cudnnGetStream 950
#define RPC_cudnnGetCallback 951
#define RPC_cudnnGraphVersionCheck 952
#define RPC_cudnnBackendCreateDescriptor 953
#define RPC_cudnnBackendDestroyDescriptor 954
#define RPC_cudnnBackendInitialize 955
#define RPC_cudnnBackendFinalize 956
#define RPC_cudnnBackendSetAttribute 957
#define RPC_cudnnBackendExecute 958
#define RPC_cudnnBackendPopulateCudaGraph 959
#define RPC_cudnnBackendUpdateCudaGraph 960
#define RPC_cudnnCreateTensorDescriptor 961
#define RPC_cudnnSetTensor4dDescriptor 962
#define RPC_cudnnSetTensor4dDescriptorEx 963
#define RPC_cudnnGetTensor4dDescriptor 964
#define RPC_cudnnGetTensorSizeInBytes 965
#define RPC_cudnnDestroyTensorDescriptor 966
#define RPC_cudnnInitTransformDest 967
#define RPC_cudnnCreateTensorTransformDescriptor 968
#define RPC_cudnnDestroyTensorTransformDescriptor 969
#define RPC_cudnnCreateOpTensorDescriptor 970
#define RPC_cudnnSetOpTensorDescriptor 971
#define RPC_cudnnGetOpTensorDescriptor 972
#define RPC_cudnnDestroyOpTensorDescriptor 973
#define RPC_cudnnCreateReduceTensorDescriptor 974
#define RPC_cudnnSetReduceTensorDescriptor 975
#define RPC_cudnnGetReduceTensorDescriptor 976
#define RPC_cudnnDestroyReduceTensorDescriptor 977
#define RPC_cudnnGetReductionIndicesSize 978
#define RPC_cudnnGetReductionWorkspaceSize 979
#define RPC_cudnnCreateFilterDescriptor 980
#define RPC_cudnnSetFilter4dDescriptor 981
#define RPC_cudnnGetFilter4dDescriptor 982
#define RPC_cudnnGetFilterSizeInBytes 983
#define RPC_cudnnDestroyFilterDescriptor 984
#define RPC_cudnnCreatePoolingDescriptor 985
#define RPC_cudnnSetPooling2dDescriptor 986
#define RPC_cudnnGetPooling2dDescriptor 987
#define RPC_cudnnGetPooling2dForwardOutputDim 988
#define RPC_cudnnDestroyPoolingDescriptor 989
#define RPC_cudnnCreateActivationDescriptor 990
#define RPC_cudnnSetActivationDescriptor 991
#define RPC_cudnnGetActivationDescriptor 992
#define RPC_cudnnSetActivationDescriptorSwishBeta 993
#define RPC_cudnnGetActivationDescriptorSwishBeta 994
#define RPC_cudnnDestroyActivationDescriptor 995
#define RPC_cudnnActivationForward 996
#define RPC_cudnnCreateLRNDescriptor 997
#define RPC_cudnnSetLRNDescriptor 998
#define RPC_cudnnGetLRNDescriptor 999
#define RPC_cudnnDestroyLRNDescriptor 1000
#define RPC_cudnnDeriveBNTensorDescriptor 1001
#define RPC_cudnnDeriveNormTensorDescriptor 1002
#define RPC_cudnnCreateSpatialTransformerDescriptor 1003
#define RPC_cudnnDestroySpatialTransformerDescriptor 1004
#define RPC_cudnnCreateDropoutDescriptor 1005
#define RPC_cudnnDestroyDropoutDescriptor 1006
#define RPC_cudnnDropoutGetStatesSize 1007
#define RPC_cudnnDropoutGetReserveSpaceSize 1008
#define RPC_cudnnGetDropoutDescriptor 1009
#define RPC_cudnnOpsVersionCheck 1010
#define RPC_cudnnGetBatchNormalizationForwardTrainingExWorkspaceSize 1011
#define RPC_cudnnGetBatchNormalizationBackwardExWorkspaceSize 1012
#define RPC_cudnnGetBatchNormalizationTrainingExReserveSpaceSize 1013
#define RPC_cudnnGetNormalizationForwardTrainingWorkspaceSize 1014
#define RPC_cudnnGetNormalizationBackwardWorkspaceSize 1015
#define RPC_cudnnGetNormalizationTrainingReserveSpaceSize 1016
