FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    nvidia-utils-550 \
    python3 \
    python3-pip \
    wget \
    curl

RUN pip3 install torch numpy --break-system-packages

COPY libcuda.so.1 /usr/local/lib/libcuda.so.1

ENV LUPINE_SERVER=71.183.65.83
ENV client_lib_path=/usr/local/lib/libcuda.so.1

COPY start.sh /start.sh

RUN chmod +x /start.sh

CMD ["/bin/bash", "/start.sh", "torch"]