name: Scuda CI

on:
  pull_request

jobs:
  tailscale_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
      
      - name: Verify Tailscale IP
        run: tailscale ip

      - name: Build and Test
        run: |
          s test

      - name: Disconnect Tailscale
        run: tailscale logout
